dataform-co/dataform

tests/api/api.spec.ts, tools/node_modules.bzl
Yarn was doing strange things. Go back to NPM which behaves as we want it to (flat node_modules) and a ton of hacks to make it work. This *should* be consistent across platforms/builds.
@BenBirt if you could test this on MacOS, that would be great!
=> Fix node module fixtures

api/commands/init.ts, api/utils.ts, cli/index.ts
Also: 
- Suggest commands when the user requests a non-existent one.
- Use nice output colours where useful.
- Require strict command setting.
- Set script name so that help output reads cleanly.
=> Fixes #124. Loudly print compile/run errors to the console.

tools/mocha/mocha_node_test.bzl, tools/mocha/mocha_runner.js
- Pass test timeouts through to the runner
- Pass test filters through to the runner
- Exit the nodejs process immediately after test completion instead of waiting for the event loop to be clear
=> Update mocha test runner to be better integrated with bazel.

api/dbadapters/index.ts, cli/index.ts
- Properly register postgres as a CLI option, fixes #185 
- Only ever print the first line of an Error's message, fixes #183 
- Exit immediately after any command completes, fixes #186
=> Various changes to make the CLI more usable.

cli/BUILD, cli/index.ts, cli/package.json, core/adapters/index.ts, package-lock.json, package.json
- Correctly interpret `~` tildes in flag paths
- In all situations that require a project directory to exist, check that it really does appear to be a dataform directory: fixes #192 
- Enable cancelling runs on non-bigquery warehouses with ctrl+C: fixes #190 
- Enable the user to simply use the default port number for redshift/postgres: fixes #191 
- Hide the asterisks that were printed as part of password entry
=> Make the CLI more usable.

docs/BUILD, tools/nginx/spa/BUILD, tools/nginx/spa/nginx.conf, tools/nginx/static/BUILD, tools/nginx/static/nginx.conf
Two new nginx configs and base nginx images built with them.
The base config for both was built by extracting the configs from the nginx docker image we were originally using.
- Remove last modified headers so we rely purely on etags instead.
- Set a 5m default cache time.
- Always serve the index file for 404's on SPAs so they can use browser history.
Unfortunately there is no easy way to compose these configs into multiple files so there is a bit of duplication.
=> Add nginx configs for static sites and single page applications

tools/nginx/spa/nginx.conf, tools/nginx/static/nginx.conf
For nextJS sites:
- for HTML files, set a cache expiry of 1d but force validation before ever serving from the cache
- for everything else (presumably behind a cachebusting URL), set a cache expiry of 1y
For the single-page app: set a cache expiry of 1d but force validation before ever serving from the cache
For posterity, these were useful:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
https://medium.com/pixelpoint/best-practices-for-cache-control-settings-for-your-website-ff262b38c5a2
https://sookocheff.com/post/api/effective-caching/
https://www.keycdn.com/blog/http-cache-headers
https://stackoverflow.com/questions/18148884/difference-between-no-cache-and-must-revalidate
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/ht …
=> Update nginx configs.

api/api.package.json, cli/cli.package.json, common.package.json, core/core.package.json, crossdb/crossdb.package.json, tools/json-merge/index.ts, tools/npm/package.bzl, version.bzl
This allows us to control dependency versions along with the package versions too.
This is so I can publish the following: https://github.com/dataform-co/dataform-co/pull/924
=> Add version substitutions for package JSON files

core/sqlx_parser.ts, examples/bigquery_language_v2/definitions/example_table.sqlx, scripts/publish, tests/api/api.spec.ts, version.bzl
=> Escape embedded expressions inside SQLX comments so that they aren't interpreted as expressions at compile-time.

core/compilers.ts, core/operation.ts, core/session.ts, core/table.ts, core/test.ts, examples/bigquery_language_v2/definitions/has_compile_errors/op_with_output_multiple_statements.sqlx, tests/api/api.spec.ts, tests/integration/snowflake.spec.ts, tests/integration/snowflake_project/definitions/load_from_s3.sqlx
Also adds support multiple queries in operations with `hasOutput`, and add a `name()` function to make it easier to work with temp tables.
=> Add an integration test that loads data into snowflake via S3.

tsconfig.json
This fixes some strange situations where using a `.includes(...)` on a `string[]` object was red-marked by the linter as an error.
=> Change tsconfig.json tslint configuration

core/assertion.ts, core/operation.ts, core/session.ts, core/table.ts, core/test.ts, core/utils.ts, examples/bigquery_language_v2/definitions/example_assertion_with_tags.sqlx, tests/core/core.spec.ts, version.bzl
- Move schema suffixing to only happen at compile()-time, after all contextable queries have run (because otherwise the code has to constantly be aware of actions that effectively have two names, one with and one without the suffix)
- Move dependency checking / qualification to compile()-time (the only safe time to do it since we allow schema overrides)
fixes https://github.com/dataform-co/dataform/issues/411
=> Fix fully-qualified dependencies.

api/commands/format.ts
- Preserve up to one empty line
- Insert a newline at EOF
for dataform-co/dataform-co#142
=> Better formatting for JS.

api/commands/format.ts, sqlx/lexer.ts
- run post-processing only after the whole file is formatted
- fix double-quote regexp lifting regexp
- push comments to their own lines
- change formatter to always place config/JS blocks first, then SQL statements, then "inner" SQL blocks
for https://github.com/dataform-co/dataform-co/issues/142
=> More formatter fixes to make it run on dataform-data.

api/commands/run.ts
- general cleanup
- never leave a Promise hanging
- run actions as soon as they become runnable
- introduce 3 layers of execution: graph/action/task
- notify listeners of an update *after* an action is added to the result, not before
for https://github.com/dataform-co/dataform-co/issues/1968
=> Refactor the Runner:

core/adapters/base.ts, core/adapters/bigquery.ts, core/adapters/redshift.ts, core/adapters/snowflake.ts, core/adapters/sqldatawarehouse.ts, core/compilers.ts, core/session.ts, core/table.ts, core/test.ts, core/utils.ts, examples/common_v2/definitions/example_is_incremental.sqlx, protos/core.proto, tests/api/examples.spec.ts, tests/core/core.spec.ts
This adds support for inline if-incremental statements. There are more use cases we are coming across where this approach makes sense.
- SQLX code is now evaluated twice in incremental tables. It's up to the user to make sure that it has no side-effects, this is a requirement I am happy to have
- This code is backwards compatible with the incremental_where behaviour
- Removes requirement for incremental_where to be set
- There is deliberately no documentation on this just yet, as it's not launch ready, but we'd like to try it in some projects
=> If incremental (alpha)

api/commands/build.ts, api/commands/prune.ts, api/index.ts, tests/api/api.spec.ts
- Introduce a prune command to apply all filters against a compiled graph
- Reduce algorithmic complexity of a lot of the filtering code significantly
- Only compute warehouse state for actions that will actually be run
=> Make building much faster

core/adapters/redshift.ts, core/utils.ts, docs/pages/guides/warehouses/redshift.mdx, protos/core.proto, tests/api/api.spec.ts, tests/core/core.spec.ts, version.bzl
This avoids possible transaction conflicts, also reduces downtime due to the fact that we have to do a drop cascade.
Fixes #227
=> Implement late binding views in redshift by default

api/commands/build.ts, core/BUILD, core/adapters/bigquery.ts, core/adapters/index.ts, core/adapters/redshift.ts, core/adapters/snowflake.ts, core/adapters/sqldatawarehouse.ts, core/core.package.json, core/session.ts, package.json, protos/core.proto, tests/api/api.spec.ts, tests/api/examples.spec.ts, tests/integration/bigquery.spec.ts, tests/integration/redshift.spec.ts, tests/integration/snowflake.spec.ts, tests/integration/sqldatawarehouse.spec.ts, version.bzl, yarn.lock
- bind changes correctness of some SQL, so we will only make it the default on versions from where it is supported.
=> Add versioning to make bind default in redshift before 1.4.1

cli/index.ts, cli/yargswrapper.ts
Fixes #394 
I also added an additional `process.exit()` for watcher SIGINT to conform with others.
Also unsure whether `process.exit()` could be substituted for `return` - CLI tests might be useful for.
=> Added exit codes to CLI, where non-zero indicates failure

core/utils.ts, scripts/run, tests/core/core.spec.ts
Fixes #421 
* Added a validation error for if a user tries to specify a `partitionBy` while the action is for `bigquery` of type `view` (BigQuery only allows `partitionBy` for type `table`).
* Added a test, similar to the existing redhshift tests, that tests that the validation error is indeed ✋💨🥎 as expected.
* Changed the `TEST_CONFIG` environment variable in tests as there are currently 3 and likely to be more in the future. See comment below.
=> Throw validation error for partitionBy if BigQuery view

contributing.md, contributors.md, readme.md
Instructions should work out the box (at least for now), preventing confusion about the `env.yaml` file if they try to build the entire solution.
I also added some info on events and such, which I think is nice.
=> Open source contribution extension

content/docs/guides/includes.md
When a function is called, it should have the file name specified
=> Fixed missing file field on function call

content/docs/guides/includes.md
When a function is called, it should have the file name specified
=> Fixed missing file field on function call (#525)

api/commands/format.ts, examples/formatter/definitions/regex.sqlx, tests/api/api.spec.ts
Fixes https://github.com/dataform-co/dataform-web-tracking/issues/204
Text lift patterns in the formatter weren't doing as they should have been, replaced them.
Added API test for formatting a file to check that it works as it should do.
=> Stop regex r format space

api/commands/build.ts, api/commands/run.ts, api/dbadapters/index.ts, api/dbadapters/redshift.ts, protos/core.proto
for https://github.com/dataform-co/dataform-co/issues/3260
See https://github.com/brianc/node-postgres/issues/1860 for why we have to do this.
I'm also getting rid of PgClientExecutor because at this point we shouldn't really be using it any longer.
=> Handle redshift query timeout errors correctly.

api/dbadapters/redshift.ts
This appears to be causing connections to terminate unexpectedly (quite how is a mystery to me).
=> Stop timing out redshift queries.

testing/BUILD, testing/hook.ts, testing/index.bzl, testing/index.spec.ts, testing/index.ts, testing/runner.ts, testing/suite.ts, testing/test.ts
Mocha causes us a few issues, as it needs to be run through the CLI, we have complex bazel rules to deal with this. It has annoyingly globally scoped types and does a lot more than we need it to.
This PR introduces a simple testing library that can be used without a CLI, where each test is simply considered a binary with a exit set according to whether it passes or not. It also adds rules `ts_test` and `ts_test_suite` for making writing bazel rules easier.
The library itself is otherwise very similar to `mocha`, without the globals, CLI, and slightly more strict usage patterns.
Features:
- Parallel test suites
- Timeouts
- Sub suites
- Hooks: beforeEach, afterEach, setUp, tearDown
- Deep diffing on log output
- Log format that matches bazel
In the future, we should I think be able to use …
=> Testing library to remove dependency on mocha

tools/grpc-web-proxy/cli.ts, tools/grpc-web-proxy/grpc-web-proxy.package.json, tools/grpc-web-proxy/index.ts, tools/grpc-web-proxy/readme.md
Because HTTP2 caused us a load of issues with certs running locally.
=> Grpc web proxy http1 support

protomongo/protomongo.go, protomongo/protomongo_test.go
Each time we encode or decode a single instance of a protobuf, we do a bunch of work involving protobuf descriptors & reflection. This PR stores the results of that work in a cache keyed by protobuf name, so that we shouldn't ever need to re-do it after computing it once.
=> Keep a cache of protobuf type Properties.

docs/pages/_docs.tsx, docs/public/robots.txt
Makes sure that when a path isn't found, it returns a 404 instead of a 500 error.
Also add an allow all robots.txt.
=> Handled 404s and add robots.txt to docs site

core/adapters/bigquery.ts, tests/api/api.spec.ts, tests/api/examples.spec.ts
Add 0 length check to `clusterBy`.
`clusterBy` wasn't set to it's default value of `[]` which is why this was missed in the tests. In order to prevent this in future nested protobufs in the API tests should be casted.
I'll look into a nice way of creating nested protobufs without having to add a huge amount of code now.
=> Clusterby length check

cli/BUILD
Adds rules for pushing a dataform docker image for use in e.g. CI tools.
See https://github.com/dataform-co/dataform-data/pull/68 for usage example (internal)
=> Add build rules for building and pushing docker images

api/commands/format.ts, examples/formatter/definitions/bigquery_regexps.sqlx, testing/runner.ts, tests/api/api.spec.ts
Fixes https://github.com/dataform-co/dataform-web-tracking/issues/218
Could probably have been 2 PRs.
Issue was caused by:
* Text being lifted and converted to hashes was globally matched, so each match was being given an identical hash.
* Regex is greedy and so would match regexes that finished in `r'`, e.g. 
```console
$ node
> "regexp_extract('bar', r'bar') as ID4 from".match(/r'.*?(?<!\\)'/g)
[ "r', r'" ]
```
whereas it should be `[ "r'bar'" ]`.
The fix I added will only accept `r'` if it has a space beforehand. This is not perfect, but I can't find the perfect solution, and this will solve for the majority of users.
* Added text for these situations.
* Differences in strings weren't showing well so I updated the testing module to show them nicer, including adding `+` and `-` symbols …
=> Fix regex hash injections and testing module improvements

protomongo/protomongo.go, protomongo/protomongo_test.go
As according to the spec: https://developers.google.com/protocol-buffers/docs/proto#updating
```
optional is compatible with repeated. Given serialized data of a repeated field as input, clients that expect this field to be optional will take the last input value if it's a primitive type field or merge all input elements if it's a message type field.
```
=> Make protomongo codec treat repeated/non-repeated fields as interoperable.

docs/components/navigation.tsx, docs/content_tree.ts, docs/layouts/documentation.tsx, docs/next.config.js, docs/pages/_docs.tsx, docs/pages/_reference.tsx, docs/pages/_web_api_reference.tsx, tools/markdown-cms/BUILD, tools/markdown-cms/github.ts, tools/markdown-cms/index.ts, tools/markdown-cms/local.ts, tools/markdown-cms/tree.ts, tsconfig.json
- Make it so that a index.md file isn't required
- Give the markdown cms library a module_name so it can be used properly
- Update references in docs
- Make the attributes generic so they can be customized (different attributes e.g. for blog posts)
- Fix tsconfig settings
- Make sure next/webpack can resolve custom module names
=> Markdown CMS fixes

tools/nginx/spa/nginx.conf, tools/nginx/static/nginx.conf
By default NGinx do compression for `text/html`.
So turning it on for `application/javascript`
https://docs.nginx.com/nginx/admin-guide/web-server/compression/
=> Turn on nginx gzip on for application/javascript

api/vm/compile.ts, cli/index.ts, version.bzl
- Print a more helpful error
- Give the user a `dataform install` command, which essentially just runs `npm i`
fixes https://github.com/dataform-co/dataform/issues/511
=> Make the CLI more helpful for projects without node_modules installed.

api/vm/compile.ts, core/utils.ts, version.bzl
I have no idea if this will fix `@dataform/cli` running on Windows more generally. I haven't been able to get the `api` tests to run because of the crazy `node_modules` rule which is not at all Windows-friendly, and I wasn't able to get a local version of `dataform-data` pointing at a bazel-built `@dataform/core`.
for https://github.com/dataform-co/dataform/issues/510
=> Make 'core' tests pass on Windows.

server/BUILD, tools/protobufjs/generate_service_defs.ts, tools/protobufjs/ts_grpc_service.bzl
- Adds a way to provide a list of root paths for resolving to imports
- Removes the default root import behaviour. This was causing all kind of weirdness and doesn't seem like we depend on it currently (or should).
=> Some tweaks to ts_gprc proto gen to handle closed-source services

content/docs/dataform-web/guides/environments.md
Example: separating development and production data into two databases
=> add section to environments

tools/nginx/spa/nginx.conf, tools/nginx/static/nginx.conf
for both `spa` and `static`: 
- `X-Content-Type-Options "nosniff"`: turn off content-type sniffing - see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
- `Strict-Transport-Security`: force browser to only use HTTPS for served domain (and subdomains), and to remember that setting for a year: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
for `static`:
- `Content-Security-Policy`: use Google's strict CSP (https://csp.withgoogle.com/docs/strict-csp.html). Turn off `object`, `applet`, and `embed` tags. Only allow `script` tags with specific SHA256 hashes, or if the browser doesn't support that, turn on `unsafe-inline`. Allow other scripts to run that have been dynamically added to the page as long as they were added by …
=> Add various headers to nginx configs to improve security.

cloudbuild-deploy.json, cloudbuild-triggers.json, scripts/cloudbuild/bazel_deploy
This defines extra gcloud triggers for when pushing to master that deploys the docs site.
- The triggers file tells cloudbuild to run this on a push to master
- The deploy script is run, and runs docs:push to push docker images
Kubernetes updates will still be applied by our closed source builds for now.
=> Auto push docs site

api/dbadapters/snowflake.ts, yarn.lock
Pending a fix for https://github.com/snowflakedb/snowflake-connector-nodejs/issues/100, this is the best we can do to set this parameter.
I'm going to check with a Snowflake rep to verify that this works as expected, but I do know (from local testing), that the `APPLICATION` parameter makes it all the way through to the Snowflake connection code, and should be set in the correct field:
```
{
"data": {
"CLIENT_APP_VERSION": "1.5.1",
"CLIENT_ENVIRONMENT": {
"http_parser": "2.8.0",
"node": "10.13.0",
"v8": "6.8.275.32-node.36",
"uv": "1.23.2",
"zlib": "1.2.11",
"ares": "1.14.0",
"modules": "64",
"nghttp2": "1.34.0",
"napi": "3",
"openssl": "1.1.0i",
"icu": "62.1",
"unicode": "11.0",
"cldr": "33.1",
"tz": "2018e",
"APPLICATION": "Dataform",
"OS": "darwin",
"OS_VERSION": "19.3.0",
"OCSP_MODE": …
```
=> Set the 'APPLICATION' parameter on Snowflake connections.

version.bzl
We are using this version number as a flag for a dfweb change - https://github.com/dataform-co/dataform-web-tracking/releases/tag/1.6.3
=> Update version to 1.6.3 for dfweb

tools/css_typings.bzl
Can't currently build css_typings rules in a repo imported from another repo. This fixes that.
dataform-co/dataform-co#5707
=> Support building css_typings inside nested repos

cli/BUILD, cli/index.ts, packages/@dataform/cli/BUILD, scripts/run, version.bzl
I'm not quite sure how to test this (seems like maybe `scripts/run` should run the JS bundle?), but I believe this fixes https://github.com/dataform-co/dataform/issues/754.
We didn't see this issue locally because `scripts/run` doesn't use the rollup bundle. I *think* that when rolled up, the `if (require.main === module)` condition always evaluates to true, so the call to `runCli()` in there also executes.
=> Remove second invocation of runCli().

api/dbadapters/snowflake.ts
Currently, creating new schemas in the non-default database fails if those schemas already exist inside the default database.
=> Check for schemas in the correct database

components/blueprint/core.global.scss
When we changed font sizes, line heights got a bit messed up. Makes card titles not be cut off
=> Increase heading line height

api/commands/build.ts, api/commands/run.ts, common/strings/stringifier.spec.ts, common/strings/stringifier.ts
For a large example graph, this drops `ExecutionGraph` size from >18MB to ~3MB.
=> Use a Set for transitive_inputs.

components/controlled_dialog.tsx
Turns out the `?` combined with a function doesn't work the way I thought 😢
=> Fix an issue with function calls on controlled dialog

components/controlled_dialog.tsx
i.e. if you're on a menu, and a menu item opens a dialog, then clicking confirm within that dialog will close the menu as well. Previously the menu stayed open.
Related to tooltip stickyness.
=> Confirm button on controlled dialog now closes the popover it came from

content/docs/guides/javascript/js-api.md
This PR simply expands the existing js file guide to include a section on referencing `includes` functions, macros and constants inside a .js file.
=> provide documentation for using js with includes

components/dialog.tsx
My bad, I didn't test this properly because I thought it was card, not dialog.
Removes warning that's something like `"isCloseButtonShown" prop is ignored if title is not set`
=> Fix dialog header

api/dbadapters/bigquery.ts
Just trying to work out why this is SO slow, I think this should help a bit.
=> Reduce bigquery pagination for listing tables

protos/core.proto
Related to https://github.com/dataform-co/dataform-co/pull/6803
Is `reserved` actually needed here?
=> Remove depricated protos for comp/val errors

content/docs/guides/configuration.md, content/docs/guides/operations.md, content/docs/guides/sqlx.md, protos/core.proto, tests/api/api.spec.ts, tests/integration/bigquery.spec.ts
To confirm, the functionality of putting it in the `dataform.json` should still exist, but its existence should just be hidden to the end user?
=> Hide singleQueryPerAction

api/dbadapters/redshift.ts, core/adapters/redshift.ts, tests/integration/redshift.spec.ts
fixes https://github.com/dataform-co/dataform/issues/259
- also stop trying to verify returned column names before we check if the query itself resulted in an error (as with assertions)
=> Always drop assertion views in Redshift before recreating them.

protomongo/protomongo.go
It looks like an update to the `github.com/golang/protobuf/proto` package changes the behaviour of `GetProperties`, and now the returned `Properties` includes the `XXX_`-prefixed properties (unknown fields, etc). 
As per the comment at the top of https://godoc.org/github.com/golang/protobuf/proto#Properties, these properties are essentially useless, and as such we filter them out.
This is required to upgrade to the latest version of Bazel.
=> Future-proof protomongo package against changes to the Go protobuf package.

.bazelrc, WORKSPACE, docs/BUILD, go.sum, packages/BUILD, protomongo/BUILD, protos/BUILD
This applies most of https://github.com/dataform-co/dataform/pull/889 without actually changing the bazel version.
=> Upgrade various dependencies to be ready for a Bazel version upgrade.

api/commands/run.ts, api/commands/test.ts, core/session.ts, tests/integration/bigquery.spec.ts, tests/integration/bigquery_project/definitions/test.js, tests/integration/redshift.spec.ts, tests/integration/redshift_project/definitions/test.js, tests/integration/snowflake.spec.ts, tests/integration/snowflake_project/definitions/test.js, tests/integration/sqldatawarehouse.spec.ts, tests/integration/sqldatawarehouse_project/definitions/test.js, tests/integration/utils.ts, version.bzl
fixes https://github.com/dataform-co/dataform/issues/908
- pull out unit test tests from overall integration tests, and parallelise all integration tests, which uncovered:
- fix a bug to do with determining what schemas should be created
- fix a bug which prevented schema suffixes working correctly for snowflake
=> Enable unit tests to compare object values.

api/BUILD, api/dbadapters/redshift.ts, tests/integration/redshift.spec.ts
- Disable parallelism on the redshift test. It appears that running two things at the same time with the same adapter is causing flakiness, haven't worked out why yet. Bug: #918
- Change "close" handler to "end" handler - as this is what's in the docs and seems to be partly the cause of #914
- Change the error handler to dispose of the connection, so that it can't be re-used. It seems like errored connections do weird things that also cause some of the issues in #914, and as it shouldn't be that common a situation, shouldn't cause too many connections to be created
- Add some better error messages to integration tests
Fixes #914
=> Redshift fixes

components/flex.scss
Setting a min-height resolves some issues with flex grow and avoids height 100% which causes a bunch of other issues (it doesn't work properly).
=> Flex grow sizing fix

scripts/publish
This isn't versioned automatically with the other dataform packages, so will cause the script to fail.
=> Remove SQL package from pubish script

api/commands/prune.ts, tests/api/api.spec.ts, tests/integration/bigquery.spec.ts, version.bzl
Fixes https://github.com/dataform-co/dataform/issues/940
Implements [this](https://dataform.canny.io/feature-requests/p/include-assertions-by-default-when-publish-tableviewincremental-is-triggered) canny request
=> Make prune keep assertions which are direct dependents of actions

api/dbadapters/redshift.ts
In previous experiments, calling query.destroy without an error didn't always cause error or end to emit. This should fix that.
=> Quick patch for redshift cancellation

components/blueprint/core.global.scss
Progresses https://github.com/dataform-co/dataform-co/issues/7625
Primary color before was too harsh, made it impossible to see tags too
=> Fix tree selected coloring

core/adapters/redshift.ts, tests/integration/redshift.spec.ts
The connection for each task is pulled fresh from the query pool, thus there is no guarantee that these statements will execute in the same connection. This appears to cause a number of issues in certain situations, as we start transactions and don't necessarily end them.
- Remove the transactions as they didn't work as intended and are causing issues.
- Make the redshift tests parallel again as this was one of the issues causing flakiness.
- Fix another issue with incremental tables that have the same name but are published in different schemas at the same time.
We should aim to reintroduce these transactions correctly, but this will require more work to make sure that subsequent tasks in an action run in the same pool connection, or possibly proper framework support for the concept of a …
=> Disable transactions for redshift incremental tables

components/breadcrumb.tsx
Intentionally haven't added `href` option because breadcrumbs should never point somewhere external
=> Add react router link to breadcrumb option

components/card.scss, components/card.tsx
Continues to downsize number of columns if the screen size is too small
=> Make number of columns in masonry view customizeable

api/commands/run.ts, api/dbadapters/bigquery.ts, api/dbadapters/index.ts, api/dbadapters/postgres.ts, api/dbadapters/redshift.ts, api/dbadapters/snowflake.ts, api/dbadapters/sqldatawarehouse.ts, api/utils/postgres.ts, core/adapters/redshift.ts, package.json, tests/api/api.spec.ts, yarn.lock
fixes https://github.com/dataform-co/dataform/issues/980
- this only applies to redshift/postgres
- there is quite a lot of code surrounding execution of individual tasks; so I settled on the pattern of a method which takes a callback; the callback is called with a single client instance which is used for the duration of `ExecutionAction` execution
- with this, I could bring back transactionality to incremental merge
=> Run all tasks in ExecutionActions using a single DB client (where applicable).

api/dbadapters/bigquery.ts, api/dbadapters/snowflake.ts, protos/core.proto
Some follow up work I noticed:
* We don't currently handle the [ARRAY type in BQ](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#array_type). Could be quite complex (you can have arrays of structs).
* We should assign a specific primitive type for RECORD and STRUCT, so that the glossary can show those types ([currently puts nothing](https://source.cloud.google.com/tada-analytics/github_dataform-co_dataform-co/+/master:ts/app/glossary/table.tsx;drc=5886f5c57f349b00541d8e1a22271cefb5adafd1;l=165)).
* Remove `primitiveDeprecated`?
Related to https://github.com/dataform-co/dataform-co/pull/7925
=> Add geography primitive type to BQ and Flake

api/commands/build.ts, api/commands/run.ts, api/commands/state.ts, api/dbadapters/bigquery.ts, api/dbadapters/index.ts
This isn't very beautiful, but does ensure that the same database (`defaultDatabase`) is used for storage/retrieval of all run caching metadata. (And besides this is all going away soon in favour of internal storage.)
=> Consistently use the project's defaultDatabase for run caching metadata.

content/docs/guides/javascript/js-api.md
Should we do this (to avoid directing people at old stuff), or keep it in for completeness?
=> remove `where()`

api/commands/state.ts
Before this fix, we would return cached metadata for *all* targets in the user's DB, which wasn't a problem except that all of that gets attached to the `ExecutionGraph` which ends up being stored in persistent storage. That can end up being *a lot* of data, e.g. in the case of our project.
(Note that this only affected projects which are using run caching.)
=> Make the state API only return cached metadata for required targets.

api/dbadapters/snowflake.ts
Fixes https://github.com/dataform-co/dataform-co/issues/8418
Information schemas aren't being hidden by the search query for the Snowflake API adapter, though they are hidden in the tableList query.
Can be replicated using our test snowflake project with this search:
=> Hide snowflake hidden schemas in search

package.json, yarn.lock
The BQ lib now has a fix (https://github.com/googleapis/nodejs-bigquery/pull/864) for https://github.com/googleapis/nodejs-bigquery/issues/857.
=> Bump BQ version past fix for 'Job Already Exists' error.

components/blueprint/core.global.scss
Progresses https://github.com/dataform-co/dataform-co/issues/8697
Doesn't make sense for it to always be white (broke in light mode), now looks like:
=> Fix menu item primary intent text color

content/docs/guides/datasets/incremental.md
A snowflake user just let me know that they assumed uniqueKey was only available to BigQuery users. Slightly tweaking the docs to try and make it clearer that it's not just a BQ feature
=> Make it clear that uniqueKey can be used when not using BigQuery

api/commands/compile.ts, api/commands/prune.ts, api/dbadapters/bigquery.ts, core/adapters/bigquery.ts, core/utils.ts
Fixes https://github.com/dataform-co/dataform-co/issues/8902
We don't actually present the database to compilation by df core, whereas it is always available when retrieving metadata from BQ.
A solution here would be to always present the database for compilation, but this blurs the lines between the API and core, as the database is stored in the credentials with many of the warehouses.
For now just not comparing database, or even removing the equality, seems best
=> Remove database from metadata target equality test, and some tidying

core/session.ts, tests/api/api.spec.ts, version.bzl
fixes https://github.com/dataform-co/dataform-co/issues/8923
=> Make it possible to compile single queries that use ref/resolve's 'rest' argument form.

api/commands/query.ts, core/compilers.ts, core/gen_index.ts, core/index.ts, tests/api/api.spec.ts, version.bzl
fixes https://github.com/dataform-co/dataform-co/issues/8925
A bit of explanation:
- in order to properly support various JS constructs, we really need to lex the query string, which is why the generated `index.js` file now calls into `compilers.ts`
- the generated `index.js` file then "calls" the compiled result inside a dynamically-constructed `Function`. (note that this is not strictly necessary, we could just `eval` the result, but `Function` makes it easier to handle multiple lines of query code)
- this means that it's possible to have full support for arbitrary JavaScript, and even `js {}` blocks
- note that the majority of the changes in `compilers.ts` is just moving code around, specifically everything inside `extractSqlxParts`; only `compileStandaloneSqlxQuery` is new
**NOTE**: …
=> Add full support for SQLX compilation to single-query compile requests.

protoc-gen-ts/README.md, protoc-gen-ts/runtime/serialize.ts, protoc-gen-ts/transpiler.ts
(required to be able to use this for `core.proto`)
=> Initialize 'decoders' after all Message classes have been declared.

api/commands/compile.ts, api/vm/compile.ts, version.bzl
[This PR](https://github.com/dataform-co/dataform/commit/2b3ef4c1b28ba0e129b52fe629539ae74e55d689) caused a conflict between socket on fd:4 and process.send.
Instead swap to just using `process.send` for all IPC.
=> Fix error piping from VM when using mac CLI

api/commands/run.ts
We do a fair bit of work on every call to `notifyListeners`, including deep-copying the whole `RunResult`, as well as triggering any code inside listener functions.
=> Only notify Runner listeners at most once every 5s.

tools/helm/helm_template.bzl
Implements #1169 .
Introduces support for materializing CRDs defined in helm chart.
Dedicated rule attribute ("include_crds") controls whether to pass
'--include-crds' flag to helm template execution - by default it is set
to false.
=> Bazel rule helm_template - support '--include-crds'

content/docs/warehouses/bigquery.md
I think the DB where the table will published to is the one overriden in config. And the read table comes from the defaultDatabase from dataform.json.
=> bigquery.md modification proposal

api/commands/compile.ts, cli/index.ts, protos/core.proto, sql/integration.spec.ts, tests/cli/cli.spec.ts, version.bzl
Fixes https://github.com/dataform-co/dataform/issues/1175
Delimited vars with colons rather than more equals because I think it looks more clear.
=> Add vars option to CLI

core/adapters/bigquery.ts
fixes https://github.com/dataform-co/dataform/issues/1196
=> Insert backticks around column names in `merge into` statements.

common/flags/index.ts
This avoids errors like `has or is using name 'SingleValueFlag' from external module ... and cannot be named`
=> Export flag classes for portability in other libraries

tools/gcloud/repository_rules.bzl
Fixes issues with `AttributeError: module 'importlib' has no attribute 'util'` when running on system using Python 3.9+.
This does now spit out the error
```
Error in atexit._run_exitfuncs:
...
ValueError: Could not find Python executable.
```
but it doesn't have an effect on actual running as it's an exit func
=> Bump gcloud version to 318.0.0

api/dbadapters/bigquery.ts, cli/credentials.ts, content/docs/getting-started-tutorial/set-up.md, content/docs/warehouses/bigquery.md, core/adapters/index.ts, protos/profiles.proto, tests/api/api.spec.ts, version.bzl
This does the following -
- Prompt the user whether they want to use application default credentials or JSON key
- If ADC, then only the projectId is requested (for billing) and credentials are an empty string
- On BigQuery() connection creation, credentials are left as empty string (use ADC) and otherwise JSON parsed.
This has been tested successfully by hand using ADC. The unit tests fail due to permission denied decrypting a key.
=> Enabling Application Default Credentials for BigQuery

package.json, yarn.lock
Lodash is probably safe to force update as all the packages are using at least `4.15` and the fixed version is in `4.17`
twinned with: https://github.com/dataform-co/dataform-co/pull/9927
=> Update a couple of packages

api/dbadapters/bigquery.ts
If I throw an error in the BQ adapter then I assume we correctly handle it, as opposed to an uncaught exception.
=> Adds error handling when query statement is empty

content/docs/warehouses/bigquery.md
Add more partitioning examples, and align clustering documentation with how BigQuery describes clustering.
=> Improve BigQuery partitioning documentation

cli/index.ts, common/protos/BUILD, core/BUILD, core/index.ts, core/session.ts, core/utils.ts, package.json, packages/@dataform/cli/BUILD, packages/@dataform/core/BUILD, packages/index.bzl, packages/rollup.config.js
- Make sure there are no known NodeJS built-ins being used when bundling the core package with rollup.
- Add a replacement for our usage of `basename` and `sep` from the `path`  built in module that works outside of Node environments.
=> Remove @dataform/core's dependency on NodeJS

cli/index.ts
There is a need to expose dependants options in CLI. It's already implemented in builder.
=> expose dependants in cli

protos/core.proto
This field is intentionally undocumented for now as this field has no effect in open-source Dataform.
=> Add defaultLocation field to dataform.json

api/commands/run.ts
Adding a new parameters to the run API:
runnerNotificationPeriodMillis (default: 5000): This optional parameter takes in the number of milliseconds the runner should wait before pushing the next run's result in order to reduce noise.
This is useful when we to stream and visualize a run's result as each action begins running.
=> Add new parameters runnerNotificationPeriodMillis to the run API

cli/index.ts, core/session.ts, examples/backwards_compatibility/dataform.json, examples/common_v1/dataform.json, examples/common_v2/dataform.json, examples/never_finishes_compiling/dataform.json, tests/api/api.spec.ts, tests/cli/cli.spec.ts, tests/core/core.spec.ts, tests/integration/bigquery_project/dataform.json, version.bzl
- Requires setting --default-location when using dataform-init
- Throws a compilation error if location is not set
=> Require defaultLocation to be set in BigQuery

content/docs/warehouses/bigquery.md
"Read the blog post" was linking to the package page and "Visit the package page" was linking to the blog post.
=> Buttons label fix

content/docs/guides/assertions.md
The example is missing the `GROUP BY` clause.
=> Update custom assertion example in assertions.md

WORKSPACE, version.bzl
Also bump some required deps. Protobuf upgrade because it was using a version of Python2 that was incompatible with other upgrades.
=> Update base dataform image to use more recent Node version

core/assertion.ts, core/common.ts, core/operation.ts, core/session.ts, core/table.ts, core/test.ts, tests/core/core.spec.ts, version.bzl
* Added schema functions to each of `ICommonContext`, `Table`, `Operation` and `Assertion`.
* Added corresponding tests
* Refactored the resolve method to de-dupe common logic in normalizing the `Schema`/`Database` and `Table` names.
* Removed redundant calls to the `toResolvable` method
=> Added schema function

core/assertion.ts, core/operation.ts, core/table.ts, tests/core/core.spec.ts
* Refactored instances of `name()` to use the newly added `finalize*()` methods in `Session`
* Added corresponding tests
Fixes #1436
=> Refactored name() function to finalize name

contributing.md
The SQL tests and directory have been removed as of #1415 and so running the given test command failed - this PR changes the command.
FIxes #1440
=> Change sample command to run tests

cli/index.ts, version.bzl
I noticed this option was missing from the help output.
=> fix missing include dependents

cli/BUILD
The docker CMD for the node image was `node`, so when no arguments we were running `dataform node`. This change makes the default `dataform help`.
Also move loads to top of file - bazel build linter was complaining.
Fixes https://github.com/dataform-co/dataform/issues/1398
=> Fix docker cmd for image

api/commands/build.ts, api/commands/compile.ts, api/commands/prune.ts, cli/console.ts, core/adapters/base.ts, core/adapters/bigquery.ts, core/adapters/index.ts, core/adapters/presto.ts, core/adapters/redshift.ts, core/adapters/snowflake.ts, core/adapters/sqldatawarehouse.ts, core/session.ts, core/table.ts, core/test.ts, core/utils.ts, protos/core.proto, tests/api/api.spec.ts, tests/api/examples.spec.ts, tests/cli/cli.spec.ts, tests/core/core.spec.ts, tests/integration/bigquery.spec.ts, tests/integration/postgres.spec.ts, tests/integration/redshift.spec.ts, tests/integration/snowflake.spec.ts, tests/integration/sqldatawarehouse.spec.ts, version.bzl
New enum field `enum_type` was added to `Table` proto message. The old field `type` marked deprecated. For backward compatibilty both fields are filled in the code when creating `CompliedGraph` representation.
=> Added enum for table's type field

cli/analytics.ts, cli/index.ts, cli/yargswrapper.ts, version.bzl
Usage: `dataform [command] --track=false`
=> Adds a flag 'track' to allow users to configure analytics with flags

api/commands/prune.ts, tests/api/api.spec.ts
This is a partial reversion of https://github.com/dataform-co/dataform/pull/959, motivated by:
1) parity with GCP Dataform
2) https://github.com/dataform-co/dataform/pull/1406 is a better way of implementing this requirement
(Cleanup, related to https://github.com/dataform-co/dataform/issues/1423)
=> Remove code which always executes auto-assertions.

core/compilers.ts, tests/core/core.spec.ts, tests/core/strings-act-literally.js.test, version.bzl
Currently (in version 2.6.1) we skip multiline string literals when creating statements in compilers.ts, and because of this in the compiled sqlx multiline strings are getting removed.
=> Include multiline string literals when creating statements

core/main.ts, core/utils.ts, version.bzl
Turns out the old version of `glob` we were using (now fixed in https://github.com/dataform-co/dataform/pull/1525), coupled with the incorrect code fixed in this PR, broke `main` compilation on Windows.
=> Fix `@dataform/core` on Windows.

core/main.ts, examples/common_v2/definitions/example_table.sqlx, examples/common_v2/includes/constants.js, version.bzl
- prevent `includes` files from implicitly depending on other `includes` files
- only `require()` top-level `includes` files
=> Tighten semantics around `require()`-ing `includes` files.

cli/console.ts, version.bzl
Adds support for NO_COLOR env variable.
When set, it disables colored output for success, warning, error and callout output.
Note: running tests has some credentials dependencies I still need to figure out, so no tests relevant for this were added.
=> Refactor colored output helpers, add support for NO_COLOR (#1517)

sandbox/compile_executor.cc
- Remove all stdout/stderr printing
- Fix some platform specific compilation issues
- Add a policy for something that happens during node in our CI/CD pipelines
=> More Sandbox2 patches

core/compilers.ts, core/utils.ts
Fixing bug for filenames not escaped in compiled graph target and canonical target : b/281045260
Testing: Could not add integration test file with a backslash because build rules doesn't allow it, but have tested manually the object: https://screenshot.googleplex.com/B4jrhURyKiyxozB
=> Fixing bug for target name not escaped

cli/index.ts, cli/vm/compile.ts, common/protos/index.ts, core/main_test.ts, core/workflow_settings.ts, tests/cli/cli.spec.ts
Include a generic best effort Protobuf field validator.
=> Validate workflow settings fields

scripts/publish, version.bzl
If we publish an alpha, beta package we don't want to mark our docker image or our npm packages as `latest` as they will then get installed by accident.
Both get marked with the `next` tag so you only get them if you explicitly ask for them.
=> Add support for publishing pre-release/next packages (and stage 2.8.0-beta.1)

cli/api/commands/run.ts, cli/api/dbadapters/bigquery.ts, cli/api/dbadapters/index.ts, cli/index.ts, protos/core.proto, tests/api/api.spec.ts
As they are not valid options for `workflow_settings.yaml`
=> Move concurrency and action retries from project config proto to the CLI

LICENSE, packages/@dataform/package.layer.json, vscode/LICENSE
Apache v2 is the default Google open source license.
This also removes the reference to Tada Science Inc as the owner.
Helps with cl/585091010.
=> Update v3 to use the apache 2.0 license

core/main_test.ts
This demonstrates that the failure to override the database via the project config vars (https://github.com/dataform-co/dataform/issues/1295) is not the fault of Dataform Core.
=> Add auto assertion database override to core test

core/main_test.ts
https://github.com/dataform-co/dataform/issues/1295
=> Add more test coverage of variables and project config overrides for Dataform Core

core/BUILD, core/actions/assertion.ts, core/actions/declaration.ts, core/actions/notebook.ts, core/actions/operation.ts, core/actions/table.ts, core/actions/test.ts, core/compilers.ts, core/main.ts, core/path.ts, core/session.ts, core/utils.ts
Including comments from https://github.com/dataform-co/dataform/pull/1595.
=> Action builders and path utils fixes

core/main_test.ts, core/workflow_settings.ts
Some more context: as detailed in the design doc for v3, pushing SQL templating out of Core means that the warehouse option is deprecated, as it will no longer have an effect.
It's kept as an exported option for now to avoid the additional work of removing it.
=> Prevent non bq warehouse from being set in workflow settings

docs/packages.md, readme.md
GitHub pages is now turned on https://dataform-co.github.io/dataform/, so the packages readme will be published via a subroute.
Content mainly copied from https://docs.dataform.co/packages/create-packages.
=> Make a packages readme

core/main.ts, core/session.ts, tests/core/core.spec.ts, version.bzl
See https://issuetracker.google.com/issues/317289296 for further details.
=> Append a compile error when `resolve()` is unable to resolve the given reference to an action.

core/actions/assertion.ts, core/actions/declaration.ts, core/actions/index.ts, core/actions/notebook.ts, core/actions/operation.ts, core/actions/table.ts, core/actions/test.ts
Facilitate this by making the action builder an abstract class.
This makes migrating the existing SQL action types to using the protobuf config types easier.
=> Move common target constructor methods to the action builder

core/actions/assertion.ts, core/actions/table.ts, core/main.ts, core/main_test.ts, core/session.ts, protos/core.proto
The tests are a bit verbose, I will parameterize them soon
=> Add action config support for the remaining SQL based action types

common/protos/index.ts, core/main_test.ts
I think this is our limit for good errors of proto validation - to improve them we'd have to swap to a type based protobuf library, and accept the performance cost.
=> Improve proto validation errors where possible

vscode/package-lock.json, vscode/package.json, vscode/server.ts
As I've discussed with @GJMcGowan in https://github.com/dataform-co/dataform/pull/1627, this PR introduces two new configration options to the VS Code dataform extension.
1. `dataform.compileOnSave` allows the user to disable the current automatic behavior of re-compiling the entire project each time an `sqlx` file is saved. I'd like to introduce this option because the notification that pops up each time compilation has finished is rather annoying. Rather than introduce the option to just silence the notification, I propose introducing the ability to disable auto-compile, as project compilation is indeed an expensive and taxing process that shouldn't just happen silently. Another reason users might want to disable the auto-compile option is to save system resources, for example when …
=> VSCode: Add ability to configure compile command, add option to skip compilation on save

packages/@dataform/core/BUILD
A suggested, trivial resolution for https://github.com/dataform-co/dataform/issues/1646.
I understand the typings were removed in https://github.com/dataform-co/dataform/pull/1552 to minimize the installed footprint of the `@dataform/core` package.
While re-adding the declarations file increases the bundle size, the size reductions introduced by #1552 would remain very similar. Before the introduction of minification, the total `node_module` size was 9.4MB. After the minifaction PR, it was ~432KB, and with the `d.ts` file re-added it would increase back to ~675KB. Instead of the original ~20x reduction, we just get a ~16x reduction. This increase can not impact compile performance, as the types file is not used during run time, so that performance gain remains.
This is just a suggestion. …
=> Include type declarations with @dataform/core

cli/api/commands/init.ts, cli/api/commands/install.ts, version.bzl
General UX:
|                      | **dataformCoreVersion present**                          | **no dataformCoreVersion present**                  |
|----------------------|------------------------------------------------------|-------------------------------------------------|
| **package.json present** | ✅ Install from dataformCoreVersion in workflow_settings.yaml | ✅ Install from @dataform/core version in package.json                |
| **no package.json**      | ✅ Install from dataformCoreVersion in workflow_settings.yaml                     | ❌ Throw error about no version definition present |
=> Update Dataform CLI npm installs to best-effort

core/session.ts, tests/core/core.spec.ts, version.bzl
The problem with support of `partitionBy` and `clusterBy` params for BigQuery materialised views seems caused just by validation rules in the core, the BigQuery adapter is able to construct valid DDL without additional modifications.
Please take a note, that I have not found a way to test it locally (construct the DDL from sqlx), will do it, if someone helps me to find guidelines how to do it (contributing.md was not enough). Otherwise, all hopes are on your CI/CD.
This fixes #1441 and partially #1334
=> Allow 'partitionBy' and 'clusterBy' params for bigquery materialized views

cli/api/commands/compile.ts, cli/api/commands/credentials.ts, cli/api/commands/run.ts, cli/api/utils/cancellable_promise.ts, cli/console.ts, cli/index.ts, cli/index_test.ts, cli/util.ts, package.json, yarn.lock
Credentials was never defaulting to the `.df-credentials` option inside the folder specified in the projectDir option, because resolve wasn't being called on projectDir.
Because resolve is called rather than just path.join, if credentialsPath is absolute, this still resolves to the absolute path, rather than attempting to join the projectDir with the absolute path.
=> Fix credentials path resolution when projectDir is specified

cli/index.ts, cli/index_test.ts, docs/configs-reference.md, protos/configs.proto
Fixes https://github.com/dataform-co/dataform/issues/1200
At some point the `tagsOption` got removed from the `run` command 👀
=> Fix CLI tags, allow comma delisted tags, add test

cli/api/commands/run.ts, cli/api/dbadapters/bigquery.ts, cli/api/dbadapters/index.ts, cli/console.ts, cli/index.ts
Fixes https://github.com/dataform-co/dataform/issues/1242
Previously dry run in the CLI would just check that the execution graph was made correctly; this now runs each action against BigQuery using the dry run API option, giving users more info on whether their jobs will succeed when actually run.
=> Extend dryrun to do dry runs against BigQuery

core/actions/assertion.ts, core/actions/index.ts, core/actions/notebook.ts, core/actions/operation.ts, core/actions/table.ts, core/compilers.ts, core/main.ts, core/main_test.ts, core/path.ts, core/session.ts, core/utils.ts, version.bzl
Fixes https://github.com/dataform-co/dataform/issues/1362#issuecomment-2022561105, which contains the explanation for this solution
Also update filename in utils to basename as it is more correct.
=> Throw errors when dots are in fields in targets

core/actions/assertion.ts, core/actions/notebook.ts, core/actions/operation.ts, core/actions/table.ts, core/main_test.ts, core/path.ts, core/utils.ts, version.bzl
Because Node isn't used in Core, Node's path computation can't be used to do this directly. To avoid redefining path resolution in yet another place, this seems like the best option.
=> Normalize paths during compilation

common/protos/index.ts, core/actions/assertion.ts, core/actions/declaration.ts, core/actions/notebook.ts, core/actions/operation.ts, core/actions/table.ts, core/actions/test.ts, core/main.ts, core/main_test.ts, core/session.ts, core/workflow_settings.ts, docs/configs-reference.md, protos/configs.proto, scripts/publish
Given that we can't do proper type validation due to ProtobufJS, this is the next best thing that I can think of.
=> Make proto object verification give more descriptive error messages

cli/index.ts
resolve https://github.com/dataform-co/dataform/issues/1747
before my pr: https://github.com/dataform-co/dataform/pull/1746
=> Enable File-Specific Formatting in dataform format

vscode/server.ts
1. Fix command name on windows to "dataform.cmd".
2. Add error handling to prevent whole extension crash.
I'm not sure how to run linter (I tried to run `scripts/lint`, but it ended up with an error `could not require "tslint-config-prettier".`), so I'd appreciate any advice you can offer.
Also, since this is my first PR to this project, please let me know if you notice any issues.
=> Fix vscode extension crashes on windows

common/protos/index.ts, core/main_test.ts
Previously this would throw an internal error of `Cannot convert undefined or null to object`. Now it throws a human readable error.
=> Fix empty object internal error

core/main_test.ts, protos/configs.proto
This will help catch issues when splitting tables to different actions, in order to support protobuf action constructors everywhere.
See https://github.com/dataform-co/dataform/pull/1760 for example of what this means.
=> Split table tests

core/BUILD, core/actions/incremental_table.ts, core/actions/index.ts, core/main.ts, core/main_test.ts, core/session.ts, core/utils.ts
Validation of these options are locked to the same functionality as before this change via these tests: https://github.com/dataform-co/dataform/blob/b3638a8134f51afdb7afed13d3786b0e2e0e98c9/core/main_test.ts#L1747C11-L1747C23
=> Incremental tables as protos, via a new class

vscode/BUILD, vscode/extension.ts, vscode/server.ts
=> Fix vscode ref issue #1768

vscode/BUILD, vscode/extension.ts, vscode/package.json, vscode/workflow_settings_yaml.schema.json
Add workflow_settings.yaml validation/completion VSCode extension.
This feature depends on 3rd party extension "redhat.vscode-yaml", so please reject this PR if you mind this point.
(I implemented the feature as optional, so the extension should work fine even without the redhat extension.)
=> Add workflow_settings.yaml validation/completion VSCode extension

cli/api/commands/run.ts
Fixes https://github.com/dataform-co/dataform/issues/1776
The dry of assertion currently fail due to the code expecting the dry run to return at least one row on [this line](https://github.com/dataform-co/dataform/blob/b3638a8134f51afdb7afed13d3786b0e2e0e98c9/cli/api/commands/run.ts#L427). 
**Tests**
1. Assertions passing by making the change in the MR. verified by running `./scripts/run run --dry-run <dataform_project_directory>`
2. Assertion when actually ran i.e. using `./scripts/run run ...` catches assertion errors 
3. `bazel test //core/...` passes 
**PS:**
This might not be the best solution, but happy to receive guidance
=> fix(1776): dry run of assertions failing

vscode/server.ts
Currently the default behaviour for when a compilation error occurs is to show a generic information message. The PR uses the graphErrors object and outputs the errors to the user similar to GCP Dataform UI 
**Current behaviour**
**New behaviour**
=> feat: vscode extension, more intutive compile errors

common/protos/index.ts, core/actions/assertion.ts, core/actions/data_preparation.ts, core/actions/incremental_table.ts, core/actions/notebook.ts, core/actions/operation.ts, core/actions/table.ts, core/actions/view.ts, core/main_test.ts, core/session.ts, core/utils.ts, version.bzl
Some fixes are:
* Notebooks can properly be dependency targets of other targets, by hacking from "location" to "dataset" fields.
* Notebooks, views and incremental tables now correctly convert dependency targets to compiled graph targets.
* Better type safeness by extracting configs proto target conversion and action configs proto conversion to separate functions.
=> Fix notebook dependency targets

packages/@dataform/core/BUILD, version.bzl
Updated dataform core package to include data preparation proto.
=> Bumped version to 3.0.1

core/compilers.ts, core/workflow_settings.ts, version.bzl
`e instanceof Error` here caused issues in internal sandbox compilation, and was also just a bad idea - this makes it safer
=> Fix catchall errors

core/actions/data_preparation.ts, core/main_test.ts, packages/@dataform/core/BUILD, protos/core.proto
Updated data preparation proto to only carry binary encoded data preparation contents after processing the data preparation definition.
=> Update output for Data Preparation processing

cli/api/commands/test.ts
This PR is linked to the following issue:
close #1791 
Prepare the following table and its corresponding unit test.
Test table:
```sql
config {
type: "table",
schema: "hoge",
name: "fuga"
}
select
user_id
from
${ref("users")}
```
Test code:
```sql
config {
type: "test",
dataset: "fuga",
}
select 1 as user_id union all
select cast(null as int64) as user_id
input "users" {
select 1 as user_id union all
select 2 as user_id
}
```
Given that the expected block includes cast(null as int64), it would be more user-friendly to have the output display as follows:
```shell
For row 1 and column "user_id": expected null, but saw "2"
```
However, the current output is as follows, which can cause confusion for the user:
```shell
For row 1 and column "user_id": expected type "object", but saw type …
```
=> Update unit test's result messages

cli/api/commands/run.ts, cli/api/dbadapters/execution_sql.ts
Solves https://github.com/dataform-co/dataform/issues/1805
1. **Tables/views:** For a view / table the metadata need not be set when doing a dry run only query validation is sufficient as metadata cannot be set if the object is not yet being materialised in BigQuery 
2. **Assertions**: No need to do `select sum(1) ...` on the view that will be created by the assertion. The query validation is sufficient to establish if the query that will be created is valid.
**Tests**
1. Dry run on assertions pass if the query is correct 
2. Dry run on assertion correctly fails if the query is not valid
3. Dry run on table/view passes if the query is valid 
4. Dry run on table/view correctly fails if the query is not valid 
5. `bazel test //core/...` passes
=> fix(1805): dry run fails when table/view/assertion already does not exists

cli/api/commands/run.ts, cli/api/dbadapters/execution_sql.ts
Reverts dataform-co/dataform#1806
This causes `//tests/integration:bigquery.spec`, instead we need `dryRun` should be passed to `assertTasks`, and only skip `select sum(1)` then
=> Revert "fix(1805): dry run fails when table/view/assertion already does not exists"

core/actions/data_preparation.ts, core/main_test.ts, protos/core.proto
The data preparation in the compiled graph now contains the resolved YAML after compiling.
I will remove the proto reference in a follow up PR.
=> Update Data Preparation processor to remove proto dependency. 

packages/@dataform/core/BUILD, version.bzl
This makes loading the current version of a downloaded package feasible in a bazel environment
=> Make published packages include the version.bzl file

scripts/publish
In GCB the default branch name used is master while we check on main to publish. This also makes more sense since we use main everywhere else as default branch.
=> Branch name from master to main

core/actions/incremental_table.ts, core/actions/view.ts, core/main_test.ts
This PR fixes a bug where `uniqueKey` assertions on views and incremental tables caused `dataform run` to exit with a query error. `uniqueKey` assertions on tables, as well as all `uniqueKeys` assertions still worked. Affected versions: `3.0.1`, `3.0.2`. I don't know whether executions on GCP were also affected.
1) Create an empty dataform project using version `3.0.1` or `3.0.2` of `@dataform/core`.
2) Add the following definition:
```
config {
type: "view",
name: "my table",
assertions: {
uniqueKey: ["id"]
}
}
SELECT 1 as id
```
3) Execute `dataform run`. Observe the following error message:
```
Table created:  dataform.my table [view]
Assertion failed:  dataform_assertions.dataform_my table_assertions_uniqueKey_0
>
>       create or replace view …
```
=> Fix `uniqueKey` assertions for views, incremental tables

cloudbuild-publish.yaml
Fix variable name to avoid conflict with GCB built-in variable names. 
This conflict was stoping release notes from publishing.
=> Change variable name in cloudbuild.yaml

cli/index.ts, common/errors/errors.ts, core/actions/data_preparation.ts, core/actions/index.ts, core/main.ts, core/main_test.ts, sqlx/lexer.ts, testing/index.ts, tests/integration/bigquery.spec.ts, vscode/extension.ts, vscode/server.ts
Hi @dataform/core 👋
Thank you for this great project! My company has been using @dataform/core as part of our data platform, and it’s been incredibly helpful.
While setting up my local development environment to fix some bugs, I found some formatting inconsistencies in the code.
Since my VSCode is configured to automatically format .ts files on save, these inconsistencies result in unintended diffs.
To avoid these diffs emerging on the bug fixes, I’d like to resolve these formatting issues first.
If there are any other behaviors or checks I need to verify, please let me know.
=> refactor: run format to all ts files

core/main_test.ts, tests/core/core.spec.ts
Individual fields under `publish` are already tested by the config parameters test, e.g. https://github.com/dataform-co/dataform/blob/b951c3807873b27ab65833cef51a6c5aa0a5f03c/core/main_test.ts#L1883.
This avoids us type locking in session the publish method - which allows updating the interface, and is safe because it's not officially supported yet https://github.com/dataform-co/dataform/issues/1168. Directly hooking in with `session` isn't really something we document.
This unblocks https://github.com/dataform-co/dataform/pull/1780.
=> Move publish tests to main_test

cloudbuild-version.yaml
Removing reviewer flag when creating a new PR. We assign `dataform-co/dataform-reviewer` as reviewer for every new PR. Trying to add this as part of create PR command was throwing error as this is not allowed.
=> Remove reviewer 

.github/workflows/test.yaml, scripts/run_integration_tests, scripts/run_tests, scripts/run_tests_on_cloudbuild, tests/api/BUILD, tests/integration/BUILD
At the moment external contributors can't run integration tests because they have no access to the GCP project used for tests. Split allows external contributors to run `./scripts/run_tests` without any issues (in fact only unit tests will run). Integration tests will run on PR.
Related issue: #1755
=> Split unit and integration tests

core/actions/data_preparation.ts
Currently unit tests are broken because #1895 introduced an unused import (I believe it was added by accident) in core/actions/data_preparations.ts
=> Remove unused import which broke unit tests.

core/actions/incremental_table.ts, core/actions/index.ts, core/actions/table.ts, core/actions/test.ts, core/actions/view.ts, core/common.ts, core/main_test.ts, core/session.ts, version.bzl
in 3.0.10 to 3.0.12, the new test cases added to `core/main.test` in this PR would throw errors - but in 3.0.9 and prior they were supported. This re-adds backwards compatibility of this support.
It also fixes some typing used, though unfortunately disabling build type safety has to be done to facilitate it.
Fixes https://github.com/dataform-co/dataform/issues/1908
Fixes https://github.com/dataform-co/dataform/issues/1907
=> Fix publish type backwards compatibility

core/actions/index.ts, core/main_test.ts, core/session.ts, docs/reference/session.md
This follows a similar model to what is already available with `publish()`, which is preferred over using the builder methods
=> Allow passing config options to assert()

core/actions/notebook.ts, core/main_test.ts, core/session.ts, docs/reference/session.md
This tests and properly configures being able to create notebooks using the JS API.
Updating the parameter structure in a backwards breaking way is fine here because:
* It was broken and untested before.
* Therefore no one was using it.
=> Add notebook js support

core/actions/assertion.ts, core/actions/data_preparation.ts, core/actions/declaration.ts, core/actions/incremental_table.ts, core/actions/notebook.ts, core/actions/operation.ts, core/actions/table.ts, core/actions/test.ts, core/actions/view.ts, core/session.ts, core/utils.ts
This prevents proto update logic from happening outside of actions. This makes action update logic more strict by having it happen inside the action files where they are configured.
=> Make action protos private

core/main_test.ts
Builds are broken currently because of https://github.com/dataform-co/dataform/pull/1923/files, this temporarily disables the test
=> Temporarily disable DataPrep validate

core/actions/data_preparation.ts, core/actions/data_preparation_test.ts, protos/configs.proto
This allows data preparations to configure override similar to all other actions.
=> Add support for schema and dataset configs in data preparation config.

core/actions/incremental_table.ts, core/actions/incremental_table_test.ts, core/main_test.ts
Configs refactoring introduced by #1780 changes the default behavior of `protected` field on Incremental tables, see #1914
The current PR changes the default behavior to make it consistent with what we had before:
1. If config has `protected` field set, then the value of the field will be used.
2. If config omits `protected` field, it will be set to false.
3. JavaScript API will be slightly __changed__: by default, `protected` will be set to false.
4. If in JavaScript API `.protected()` will be called without arguments (like it was possible before) then the field will be set to through.
5. If in JavaScript API `.protected()` will be called with argument (true or false) then the field will be set to the value of the argument passed.
The logic is quite complicated here but we are trying to …
=> Make  field on Incremental tables default to false as it was before.

cli/api/commands/run.ts, cli/api/dbadapters/bigquery.ts, cli/api/dbadapters/index.ts, cli/console.ts, contributing.md
Solves: https://github.com/dataform-co/dataform/issues/1944
Shows BigQuery jobId against each ran model as follows. Happy to change the format the jobId is displayed 
**Tests**
**P.S.**
It will be good to have have the jobIds as hyperlinks but most default terminal emulators do not support this. From the terminals I have only Kitty supported it. Default MacOS terminal and Ghostty terminal did not support it.
=> feat: show bigquery jobId when executing the job

core/actions/assertion.ts, core/actions/incremental_table.ts, core/actions/operation.ts, core/actions/table.ts, core/actions/view.ts, core/main_test.ts, core/utils.ts
Legacy dependencies with a qualified names like: `dataset_name.table_name` wasn't resolved  correctly, see #1896 
The current change fixes this behavior and properly parses `config.dependencies` when it contains string values.
=> fix: Correctly resolve legacy dependencies with qualified name.

cli/console.ts, cli/index.ts, cli/index_test.ts
This PR implements the Feature Request to add a `--check` flag to the `format` command.
- Added a new `--check` flag to the format command
- Modified the format command implementation to support check mode without modifying files
- Enhanced the output formatting to clearly show which files need formatting
- Made the command return exit code 1 if any files need formatting in check mode
When used with `--check`, the command:
1. Analyzes each file that would be formatted
2. Compares the current content with what it would be if formatted
3. Reports files needing formatting without modifying them
4. Returns exit code 1 if any files need formatting
```bash
dataform format --check
dataform format --check --actions="definitions/my_model.sqlx" 
```
I've tested both the regular format mode (which …
=> Add `--check` option to format command

cli/index.ts
Fixes: https://github.com/dataform-co/dataform/issues/1945
Show user a log message that there is no actions to run instead of prematurely showing running
Tests
=> fix(actions): gracefully exit when no actions to run

cli/api/commands/build.ts, cli/api/dbadapters/execution_sql.ts, tests/api/api.spec.ts
According to the documentation in https://cloud.google.com/dataform/docs/reference/dataform-core-reference#itableconfig:
> __protected__ | boolean
>
> Only allowed for the incremental table type. If set to true, running this action ignores the full-refresh option. This is useful for tables which are built from transient data, to ensure that historical data is never lost.
Our current behavior: the `run` command of Dataform CLI fails with an error `Protected datasets cannot be fully refreshed.` However, on GCP the behavior is correct and the action is executed in incremental mode (basically ignoring `full refresh`).
This PR makes CLI behavior aligned with the documentation and GCP.
Closes #1892.
=> Protected incremental table ignores full-refresh

cli/util.ts, cli/util_test.ts
Solves: https://github.com/dataform-co/dataform/issues/1993
Moves the metadata (jobId, Bytes billed) of dataform run for table/view/operation to a new line and indented to the right making the output more readable. 
**Tests**
=> feat: improve formatting for `dataform run` stdout

core/actions/incremental_table.ts, core/actions/incremental_table_test.ts, core/actions/table.ts, core/actions/table_test.ts, core/utils.ts, core/utils_test.ts, core/workflow_settings.ts, protos/configs.proto, protos/core.proto
This change allows users to set defaultBucketName, defaultTableFolderRoot and defaultTableFolderSubpath in workflow_settings.yaml. These fields are parsed and stored as part of projectConfig. If no alternative values are provided inside the user's config block, we use the defaults defined inside workflow_settings.yaml. If the default values inside workflow_settings.yaml are also not provided, we fall back to preexisting defaults.
=> Enable setting default values for storageUri substrings when constructing an Iceberg table.

core/utils.ts, core/utils_test.ts
This change ensures users can provide the fileFormat string in any case.
=> Make Iceberg fileFormat compilation case insensitive

core/actions/incremental_table.ts, core/actions/incremental_table_test.ts, core/actions/table.ts, core/actions/table_test.ts, core/utils.ts, core/utils_test.ts, core/workflow_settings.ts, protos/configs.proto
This change enables a workflow-level default connection to be set inside workflow_settings.yaml.
=> Enable setting default connection for Iceberg table
