- cli/index.ts
This change should introduce no actual change in the CLI.
> Overhaul CLI construction for clarity & type-safety.

- api/commands/build.ts
- api/commands/run.ts
- api/package.json
- cli/index.ts
- cli/package.json
- core/adapters/bigquery.ts
- core/adapters/redshift.ts
- core/adapters/snowflake.ts
- core/package.json
- crossdb/package.json
- examples/bigquery/package.json
- examples/bigquery_with_errors/package.json
- examples/redshift/package.json
- examples/redshift_operations/package.json
- examples/snowflake/package.json
- protos/package.json
- tests/api/api.spec.ts
- Fixes issues with suffixed schemas not being created, and being ignored in some SQL generation code.
- Fixes issue with compilation errors being incorrectly detected when there are none on the CLI.
- Bumps the dataform version to 0.1.0-rc.
> Release candidate for version 0.1.0 with a handful of bug fixes.

- docs/pages/guides/js-api.mdx
> Fix documentation example of the 'operate' API so that it works.

- cli/index.ts
- docs/pages/guides/command-line-interface.mdx
> Update CLI documentation to match different output.

- core/compilers.ts
- tests/core/core.spec.ts
> Change regex to fix the issue #171

- api/commands/build.ts
- tests/api/api.spec.ts
> Prevent protected datasets from being fully refreshed.

- docs/components/header.tsx
- docs/layouts/base.tsx
- docs/pages/_document.tsx
- docs/pages/guides/command-line-interface.mdx
- docs/pages/guides/configuration.mdx
- docs/pages/guides/core-concepts.mdx
- docs/pages/guides/includes.mdx
- docs/pages/guides/warehouses/bigquery.mdx
- docs/pages/guides/warehouses/redshift.mdx
- docs/pages/index.mdx
- docs/pages/platform_guides/set_up_datawarehouse.mdx
Fixes #234 and makes docs a little better with some html changes.
> Adds analytics to docs

- package-lock.json
- package.json
- tools/json-merge/index.ts
> Remove axios vulnerability. Make it possible to use this code locally in a dataform-co build again.

- package-lock.json
- package.json
- tools/json-merge/index.ts
Urgh, I was wrong, I had run //bazel test tests/integration:bigquery in the wrong branch, this commit broke it
> Revert "Remove axios vulnerability. Make it possible to use this code locally in a dataform-co build again."

- api/api.package.json
- cli/cli.package.json
- common.package.json
- core/core.package.json
- core/sqlx_parser.ts
- examples/bigquery_language_v2/definitions/example_js_blocks.sqlx
- tests/api/api.spec.ts
> Fix SQLX lexing to allow the user to specify multiple JS blocks.

- docs/pages/guides/assertions.mdx
corrected error in with statement syntax
> corrected syntax of with statement

- cli/index.ts
> Always run a final iteration of printing out any (as yet unprinted) actions after completion of 'dataform run'.

- api/api.package.json
- cli/cli.package.json
- common.package.json
- core/adapters/redshift.ts
- core/core.package.json
- crossdb/crossdb.package.json
fixes https://github.com/dataform-co/dataform/issues/259
> Drop views in Redshift to allow for changes to the view's columns (and their types).

- api/commands/validate.ts
- api/index.ts
- tests/api/validate.spec.ts
- tests/utils/BUILD
- tests/utils/fixtures.ts
Also updating the validation error message to make it more understandable to user.
> Add validateSchedulesFile method

- .bazelrc
- BUILD
- WORKSPACE
- cloudbuild.json
- package.json
- tools/css_typings.bzl
- tools/next_site.bzl
- tools/node_modules.bzl
- yarn.lock
> Bazel 0.27

- core/session.ts
- tests/api/api.spec.ts
- version.bzl
> Make schema suffixes work correctly for files with explicitly overridden schemas.

- docs/pages/guides/assertions.mdx
- docs/pages/guides/configuration.mdx
- docs/pages/guides/js-api.mdx
https://github.com/dataform-co/dataform-co/issues/754
> Remove dead links to reference documentation.

- docs/components/navigation.tsx
- docs/pages/platform_guides/scheduling.mdx
Reverts dataform-co/dataform#285
> Revert "Remove scheduling page from the docs site"

- examples/redshift_never_finishes_compiling/BUILD
- examples/redshift_never_finishes_compiling/dataform.json
- examples/redshift_never_finishes_compiling/definitions/test.js
- examples/redshift_never_finishes_compiling/package.json
- tests/api/BUILD
- tests/api/api.spec.ts
> Add a testcase which times out during compilation.

- api/commands/test.ts
- api/index.ts
- core/assertion.ts
- core/index.ts
- core/operation.ts
- core/session.ts
- core/table.ts
- core/test.ts
- examples/bigquery_language_v2/definitions/actual_test.js
- protos/core.proto
- tests/api/api.spec.ts
- tests/integration/bigquery.spec.ts
- tests/integration/bigquery_project/definitions/test.js
- tests/integration/redshift.spec.ts
- tests/integration/redshift_project/definitions/test.js
- tests/integration/snowflake.spec.ts
- tests/integration/snowflake_project/definitions/test.js
- does not support any queries that are not datasets
- does not yet support incremental tables (this needs a little thought!)
- TODO: add SQLX support
- TODO: expose a new `test` command in CLI once SQLX support exists
> Add initial dataset test case support.

- cli/console.ts
> Fix CLI to understand Operations without 'target' fields.

- assertion_utils/.gitignore
- assertion_utils/BUILD
- assertion_utils/assertion_utils.package.json
- assertion_utils/index.ts
- tests/integration/bigquery.spec.ts
- tests/integration/bigquery_project/BUILD
- tests/integration/bigquery_project/definitions/example_assertion_pass.assert.sql
- tests/integration/bigquery_project/definitions/example_assertion_pass.sqlx
- tests/integration/bigquery_project/definitions/example_assertion_uniqueness_fail.sqlx
- tests/integration/bigquery_project/definitions/example_assertion_uniqueness_pass.sqlx
- tests/integration/bigquery_project/definitions/sample_data_2.sqlx
- tests/integration/redshift.spec.ts
- tests/integration/redshift_project/BUILD
- tests/integration/redshift_project/definitions/example_assertion_pass.assert.sql
- tests/integration/redshift_project/definitions/example_assertion_pass.sqlx
- tests/integration/redshift_project/definitions/example_assertion_uniqueness_fail.sqlx
- tests/integration/redshift_project/definitions/example_assertion_uniqueness_pass.sqlx
- tests/integration/redshift_project/definitions/sample_data_2.sqlx
- tests/integration/snowflake.spec.ts
- tests/integration/snowflake_project/BUILD
- tests/integration/snowflake_project/definitions/example_assertion_pass.assert.sql
- tests/integration/snowflake_project/definitions/example_assertion_pass.sqlx
- tests/integration/snowflake_project/definitions/example_assertion_uniqueness_fail.sqlx
- tests/integration/snowflake_project/definitions/example_assertion_uniqueness_pass.sqlx
- tests/integration/snowflake_project/definitions/sample_data_2.sqlx
keyUniqueness if the only function for now!
> added assertion_utils

- api/BUILD
- api/commands/compile.ts
- api/vm/compile.ts
- cli/BUILD
- tools/json-merge/BUILD
fixes https://github.com/dataform-co/dataform-web-tracking/issues/153
> Write compiled output to a randomly generated filename.

- api/commands/run.ts
- api/commands/state.ts
- api/commands/table.ts
- api/commands/test.ts
- api/dbadapters/bigquery.ts
- api/dbadapters/index.ts
- api/dbadapters/redshift.ts
- api/dbadapters/snowflake.ts
- tests/api/api.spec.ts
- tests/integration/utils.ts
for https://github.com/dataform-co/dataform-co/issues/868
> Add an API to preview a table, implement it for BigQuery. (Note that this only works for tables, not views.)

- api/commands/table.ts
- api/dbadapters/bigquery.ts
- api/dbadapters/index.ts
- api/dbadapters/redshift.ts
- api/dbadapters/snowflake.ts
for https://github.com/dataform-co/dataform-co/issues/868
> Finish preview() API for non-table BigQuery datasets & datasets belonging to other warehouses.

- api/dbadapters/bigquery.ts
Fixes: https://github.com/dataform-co/dataform-co/issues/879
> Fix other bigquery date related field preview

- cli/index.ts
- docs/pages/guides/command-line-interface.mdx
Let me know if there are any other commands which require changing the CLI documentation.
> Add yargs doc for `dataform help` command. Few fixes. [#307]

- core/test.ts
- version.bzl
for https://github.com/dataform-co/dataform/issues/344
> Don't return early (before returning a proto) if Test compilation fails for some reason.

- core/operation.ts
- core/test.ts
- core/utils.ts
- examples/bigquery_language_v2/definitions/example_test_case.sqlx
- version.bzl
for https://github.com/dataform-co/dataform/issues/344
>  Correctly report filenames in compilation Errors created in compile().

- api/dbadapters/sqldatawarehouse.ts
- version.bzl
Fixes https://github.com/dataform-co/dataform/issues/365
> Fix preview query for SqlDataWarehouse

- core/assertion.ts
- core/operation.ts
- core/session.ts
- core/table.ts
- tests/core/core.spec.ts
- version.bzl
Let's keep #357 so that it can be included on Thu production cut.
> Fix issue #357 (P1)

- api/commands/compile.ts
- api/vm/compile.ts
I've tested this on a graph containing >1000 actions, everything seems to work. If you've other testing suggestions, let me know...
> Pipe CompiledGraph results back to the parent process instead of using a file.

- api/commands/query.ts
- api/commands/run.ts
- api/dbadapters/bigquery.ts
- api/dbadapters/index.ts
- api/dbadapters/sqldatawarehouse.ts
- tests/api/api.spec.ts
- tests/integration/bigquery.spec.ts
- tests/integration/redshift.spec.ts
- tests/integration/snowflake.spec.ts
- tests/integration/sqldatawarehouse.spec.ts
- tests/integration/utils.ts
fixes https://github.com/dataform-co/dataform/issues/374
> For interactive queries, don't use BigQuery jobs.

- api/commands/compile.ts
for https://github.com/dataform-co/dataform-co/issues/1437
> Run validity checks on ProjectConfig after merging with any override that may be set.

- core/gen_index.ts
- core/session.ts
- version.bzl
fixes https://github.com/dataform-co/dataform/issues/404
> Remove implicit protobuf package dependencies from all Dataform projects.

- core/table.ts
- examples/bigquery_language_v2/definitions/example_incremental.sqlx
- tests/api/api.spec.ts
- version.bzl
fixes https://github.com/dataform-co/dataform/issues/414
> Make the 'protected' setting work.

- api/commands/init.ts
- cli/index.ts
- protos/core.proto
- tests/api/validate.spec.ts
For: https://github.com/dataform-co/dataform/issues/415
> Add environments proto and json file

- api/commands/format.ts
for dataform-co/dataform-co#142
> Fix the formatter to always place JS placeholders on newlines.

- api/commands/format.ts
- remove whitespace between `${` / `}` and the first/last character in formatter result (for single line formatter results)
- only push placeholders onto their own lines if they expand to more than one line
for dataform-co/dataform-co#142
> Clean up formatter results for single-line replacements.

- api/commands/format.ts
for https://github.com/dataform-co/dataform-co/issues/142
> Fix the formatter for BigQuery regexps.

- api/dbadapters/bigquery.ts
> Fixes an issue where a null date from bigquery would cause the query to fail

- api/dbadapters/redshift.ts
For: https://github.com/dataform-co/dataform-web-tracking/issues/190
Things to note:
It seems there is no table type. So considering all the table as `table`
Related documentation from AWS:
https://docs.aws.amazon.com/redshift/latest/dg/r_SVV_EXTERNAL_COLUMNS.html
https://docs.aws.amazon.com/redshift/latest/dg/r_SVV_EXTERNAL_TABLES.html
> Get datasets from Redshift Spectrum

- api/commands/query.ts
- api/commands/run.ts
- api/commands/test.ts
- api/dbadapters/bigquery.ts
- api/dbadapters/index.ts
- api/dbadapters/snowflake.ts
https://github.com/dataform-co/dataform-co/issues/1929
> Limit returned row count for Snowflake and BQ (interactive) queries.

- api/dbadapters/sqldatawarehouse.ts
https://github.com/dataform-co/dataform-co/issues/1929
> Make sqldatawarehouse DB adapter obey limit parameter.

- docs/components/navigation.tsx
- docs/pages/platform_guides/environments.mdx
for https://github.com/dataform-co/dataform-co/issues/1623
> Add a docs page on environments.

- api/commands/run.ts
for dataform-co/dataform-co#1968
> Bring back SKIPPED action logic, and handling run cancellation in the Runner.

- api/commands/run.ts
- cli/console.ts
- cli/index.ts
- tests/api/api.spec.ts
- tests/integration/bigquery.spec.ts
- tests/integration/redshift.spec.ts
- tests/integration/snowflake.spec.ts
- tests/integration/sqldatawarehouse.spec.ts
for dataform-co/dataform-co#1968
> Finally convert Runner interface to use new protobufs.

- api/dbadapters/bigquery.ts
fixes https://github.com/dataform-co/dataform-co/issues/1999
> Fix interactive queries on BigQuery.

- api/dbadapters/redshift.ts
Possible fix, or at least workaround for  #458
I've filed a bug hoping to get some more thoughts on this in the pg-cursor library: https://github.com/brianc/node-pg-cursor/issues/55
For our failing project (the demo project) this seems to have fixed the underlying issue for now.
> Always request at least 2 rows from the cursor (Redshift)

- api/dbadapters/redshift.ts
for https://github.com/dataform-co/dataform-co/issues/2062
> Handle errors from idle pg.Pool clients.

- api/dbadapters/redshift.ts
for https://github.com/dataform-co/dataform-co/issues/2062
> Add error handler for pg.Client objects.

- api/dbadapters/redshift.ts
for https://github.com/dataform-co/dataform-co/issues/2062
> Stop using pg connection pools.

- tools/grpc-web-proxy/BUILD
- tools/grpc-web-proxy/cli.ts
- tools/grpc-web-proxy/grpc-web-proxy.package.json
- tools/grpc-web-proxy/index.ts
- tools/grpc-web-proxy/readme.md
This is a pure node implementation of gRPC web proxy. It's pretty alpha, but I need it for a few projects / want to share with world.
> Add a node gRPC web proxy package

- core/BUILD
- core/core.package.json
- core/session.ts
- package.json
- version.bzl
- yarn.lock
for https://github.com/dataform-co/dataform-co/issues/2392
> Use Tarjan's strongly connected component algorithm to compute cycles.

- api/dbadapters/redshift.ts
- api/dbadapters/snowflake.ts
- api/dbadapters/sqldatawarehouse.ts
for https://github.com/dataform-co/dataform-co/issues/2413
> Increase the limit on the number of returned tables for {Redshift,Snowflake,SQLDataWarehouse} to 10000.

- .bazelrc
- cloudbuild.json
- tools/ts_proto_library.bzl
- make necessary changes so that the code now compiles
> Upgrade bazel version to latest in the docker registry (v1.1).

- api/commands/state.ts
- api/dbadapters/bigquery.ts
- api/dbadapters/redshift.ts
- api/dbadapters/snowflake.ts
- api/dbadapters/sqldatawarehouse.ts
> Changes warehouse state calculation to throw an error instead of swallowing it

- api/dbadapters/redshift.ts
> Only query for spectrum tables when they exist

- docs/pages/guides/documentation.mdx
- protos/core.proto
> Replace left and right double quotation marks with regular

- docs/algolia.json
- docs/pages/_reference.tsx
> Excluded versioned parts of the docs site from indexing

- api/dbadapters/redshift.ts
As per https://node-postgres.com/api/client
> Set a query timeout on all redshift queries of 1 hour max.

- api/dbadapters/bigquery.ts
- api/dbadapters/redshift.ts
Reverts dataform-co/dataform#559
> Revert "Stop timing out redshift queries."

- docs/cms/github.ts
- docs/cms/local.ts
Somehow list the extension stripping code here!
> Fix docs site URLs

- protomongo/protomongo.go
for https://github.com/dataform-co/dataform-co/issues/3621
> Prefix encoded field names when using protomongo codec.

- cli/index.ts
> Fix printing of unhandled promise rejections

- core/adapters/base.ts
- tests/api/api.spec.ts
fixes https://github.com/dataform-co/dataform/issues/593
> Fix incremental pre/post ops.

- testing/runner.ts
- testing/test.ts
I have no idea how to write tests for this :P
> Make test filtering using Bazel's --test_filter flag work.

- content/docs/how-to-guides/warehouses/bigquery.md
- core/adapters/bigquery.ts
- core/table.ts
- core/utils.ts
- examples/common_v2/definitions/has_compile_errors/assertion_with_bigquery.sqlx
- protos/core.proto
- tests/api/api.spec.ts
- tests/core/core.spec.ts
Fixes https://github.com/dataform-co/dataform-co/issues/3889
API changes, tests changes, and docs updates.
> Add cluster by

- api/dbadapters/bigquery.ts
- version.bzl
> Deal with default values for gcloud projectId correctly

- content/docs/dataform-web/guides/git-access-tokens.md
I bet the emojis are controversial
> Git access tokens docs improvement

- api/commands/run.ts
- api/dbadapters/bigquery.ts
Fixes: https://github.com/dataform-co/dataform-co/issues/4412
> Skip disabled action during storing metadata

- core/table.ts
- version.bzl
fixes https://github.com/dataform-co/dataform/issues/647
> Fix assertions-in-config-block when user sets zero row assertions.

- api/dbadapters/bigquery.ts
- api/utils/error_parsing.ts
Fixes https://github.com/dataform-co/dataform-co/issues/4178
Error only seems to happen in BQ projects.
> Stop bq false line number

- cli/index.ts
> Look for credentials in the project-dir when provided

- api/commands/run.ts
- tests/integration/bigquery.spec.ts
for https://github.com/dataform-co/dataform-co/issues/4903
> Temporarily switch off pushing dataset descriptions to BQ.

- api/commands/compile.ts
- core/session.ts
- protos/core.proto
- tests/core/core.spec.ts
- version.bzl
open source part of #4769
I managed to test it all the way through with the frontend and it seemed to work
> Adds the 'tablePrefix' to the projectConfig

- api/commands/run.ts
- tests/integration/bigquery.spec.ts
- tests/integration/bigquery_project/definitions/depends_on_example_view.sqlx
Fixes: https://github.com/dataform-co/dataform-co/issues/4902
> Fix run cache when downstream is supposed to run if upstream changed

- api/dbadapters/redshift.ts
This is a bit of a hack, but will quickly help us debug why some user(s) aren't able to get set up using redshift.
> Include (some) query strings in Errors thrown by redshift DB adapter.

- core/adapters/redshift.ts
- tests/api/api.spec.ts
> Don't set with no schema binding in PG

- core/common.ts
- core/session.ts
- core/table.ts
- protos/core.proto
Small PR for protos. Does everything look right?
> Navigator sqlx protos

- core/session.ts
- tests/core/core.spec.ts
- version.bzl
> Fixes issue with tablePrefix and ref/resolve

- protos/core.proto
- protos/schedules.proto
for https://github.com/dataform-co/dataform-co/issues/5333
> Add new protobufs for schedules-in-environments.

- tools/markdown-cms/github.ts
- tools/stackdriver-github-bridge/index.ts
- yarn.lock
> Upgrade and fix octokit usage

- cli/index.ts
- tests/cli/BUILD
- tests/cli/cli.spec.ts
- version.bzl
> Add fix and test for undefined warehouse issue

- protos/core.proto
for https://github.com/dataform-co/dataform-co/issues/5333
> Add a combined git reference field, deprecate the old one.

- common/strings/stringifier.ts
- sql/builders/aggregate.ts
- sql/builders/from.ts
- sql/builders/join.ts
- sql/integration.spec.ts
Tidies up some formatting output
> A few tweaks for SQL builders

- api/BUILD
- api/commands/build.ts
- api/commands/run.ts
- api/dbadapters/bigquery.ts
- api/utils/graphs.ts
- protos/core.proto
- tests/api/api.spec.ts
- tests/api/examples.spec.ts
for https://github.com/dataform-co/dataform-co/issues/5711
> Replace ExecutionAction.dependency_targets with ExecutionAction.transitive_inputs.

- components/breadcrumb.tsx
Can do this with CSS if you prefer
for https://github.com/dataform-co/dataform-co/issues/5333
> Add more spacing around breadcrumb chevrons.

- components/collapse.tsx
for https://github.com/dataform-co/dataform-co/issues/5333
> Allow configuring styles with SimpleCollapse.

- components/controlled_dialog.tsx
- components/forms.tsx
Needed to pull controlled dialog into here to use it in navigator, also changes some props around
> Add controlled dialog

- components/breadcrumb.tsx
- components/card.tsx
- components/list.scss
- components/list.tsx
Supplements for https://github.com/dataform-co/dataform-co/pull/6170
* Allow horizontally flowing list items
* Add breadcrumbs option to top of a card
> Breadcrumb tweaks

- api/utils/graphs.ts
Connected to [this comment](https://github.com/dataform-co/dataform-co/pull/6248#discussion_r433682428)
> Add graph functions

- api/dbadapters/bigquery.ts
- api/dbadapters/redshift.ts
- tests/integration/snowflake.spec.ts
And wrap a few errors with causes.
> Try to fix async error routing for some bigquery code paths

- sql/builders/aggregate.ts
- sql/index.ts
- sql/integration.spec.ts
- Fix trailing commas
- Safe divide
- Varchar instead of string for postgres
- Tests
dataform-co/dataform-co#6392
> More SQL tweaks

- tools/protobufjs/generate_service_defs.ts
Async stack traces only work when thrown in async methods, so we'll need to wrap non async/await third party libs like this.
> Wrap grpc code for nice async stack traces

- components/charts/common.tsx
- sql/index.ts
Allow null literals, and support null values returned for charts.
> Support nulls as values

- .bazelrc
Fixes dataform-co/dataform-co#6823
> Use buildfarm

- core/column_descriptors.ts
Should be here rather than [here](https://github.com/dataform-co/dataform-co/blob/f788b67b3ed2f54502b269f416f1a9af973f0a9b/ts/app/sqlx/sqlx_editor.ts#L184)
> Add map from for aggregation and dimension type

- api/dbadapters/snowflake.ts
https://github.com/dataform-co/dataform-co/issues/6939
> Make Snowflake send us a heartbeat message every 30s.

- api/dbadapters/bigquery.ts
Should have been like this in first place, motivation to fix was getting errors without any explanation like `Failed to build execution graph: Error getting BigQuery metadata.`.
> Replace some errorswithcause with coerceAsError

- api/dbadapters/bigquery.ts
- tests/integration/snowflake.spec.ts
Saw some flakes in https://console.cloud.google.com/cloud-build/builds/598e3754-34f6-48cb-97cc-a208e43bc206;step=1?project=dataform-public, decided to try and fix / make more visible
> Address some test flakiness.

- api/commands/build.ts
for https://github.com/dataform-co/dataform-co/issues/6939
> Revert state-fetch behaviour for projects which do not turn on run caching.

- yarn.lock
https://github.com/dataform-co/dataform/network/alert/yarn.lock/kind-of/open
> Fix kind-of security alert.

- api/dbadapters/snowflake.ts
for https://github.com/dataform-co/dataform-co/issues/6939
As requested by Snowflake support, and listed here: https://community.snowflake.com/s/article/How-to-generate-log-file-on-Snowflake-connectors
To get these logfiles we will need to copy them from k8s.
> Configure Snowflake client to write out trace-level logs.

- api/commands/run.ts
- cli/index.ts
- common/promises/BUILD
- common/promises/index.spec.ts
- common/promises/index.ts
- tests/api/BUILD
- tests/api/api.spec.ts
- tests/integration/bigquery.spec.ts
- tests/integration/redshift.spec.ts
- tests/integration/snowflake.spec.ts
- tests/integration/sqldatawarehouse.spec.ts
for https://github.com/dataform-co/dataform-co/issues/7010
- also bring `Promise` utilities into open-source
> Make runs resumable.

- api/commands/compile.ts
for https://github.com/dataform-co/dataform-co/issues/6964
> Include cause error message in compile ErrorWithCause.

- api/dbadapters/bigquery.ts
- api/dbadapters/index.ts
- api/dbadapters/redshift.ts
- api/dbadapters/snowflake.ts
- api/dbadapters/sqldatawarehouse.ts
Fixes https://github.com/dataform-co/dataform-co/issues/7007
Presumably the user knows which warehouse they're using
> Fix warehouse error names

- components/collapse.tsx
Prep for https://github.com/dataform-co/dataform-co/issues/7031
> Add start open back to simple collapse

- api/dbadapters/redshift.ts
fixes https://github.com/dataform-co/dataform-co/issues/6885
> Make Redshift/postgres throw an error if they run a query that results in duplicate column names.

- components/collapse.tsx
- components/controlled_dialog.tsx
- components/error_boundary.tsx
- components/list.tsx
For https://github.com/dataform-co/dataform-co/pull/7071
> Make component props exported

- components/collapse.tsx
Should have added in https://github.com/dataform-co/dataform/pull/865, mb
> Make collapse message optional

- api/dbadapters/redshift.ts
- api/dbadapters/snowflake.ts
- api/dbadapters/sqldatawarehouse.ts
fixes https://github.com/dataform-co/dataform/issues/667
> Make query cancellation work for redshift & snowflake.

- api/commands/build.ts
- cli/console.ts
- core/assertion.ts
- core/common.ts
- core/compilers.ts
- core/declaration.ts
- core/operation.ts
- core/session.ts
- core/table.ts
- core/test.ts
- protos/core.proto
- tests/api/examples.spec.ts
- tests/core/backslashes-act-literally.js.test
- tests/core/basic-syntax.js.test
- tests/core/strings-act-literally.js.test
- version.bzl
fixes https://github.com/dataform-co/dataform/issues/326
> Make it possible to disable operations and assertions.

- api/dbadapters/bigquery.ts
- api/dbadapters/redshift.ts
- api/dbadapters/snowflake.ts
- api/dbadapters/sqldatawarehouse.ts
- core/adapters/base.ts
- core/adapters/bigquery.ts
- core/adapters/index.ts
- core/adapters/redshift.ts
- core/adapters/snowflake.ts
- core/adapters/sqldatawarehouse.ts
- protos/core.proto
- tests/api/api.spec.ts
- tests/integration/redshift.spec.ts
- tests/integration/utils.ts
There are a number of bugs around schema type detection that we are running into with config generation, this is the groundwork for fixing that.
> Add proper enums for table and field metadata

- core/gen_index.ts
- core/index.ts
- examples/common_v1/includes/example_ignore.js
- tests/api/examples.spec.ts
- version.bzl
for https://github.com/dataform-co/dataform/issues/423
> Stop silently swallowing errors caused by require()ing broken 'includes' files.

- api/commands/format.ts
Prep for https://github.com/dataform-co/dataform-co/issues/6084
> Expose formatter for file content

- core/compilers.ts
- tests/core/backticks-are-escaped.js.test
- tests/core/core.spec.ts
- version.bzl
fixes https://github.com/dataform-co/dataform/issues/818
> Escape backticks inside SQLX literal strings.

- api/dbadapters/bigquery.ts
- api/dbadapters/index.ts
- api/dbadapters/redshift.ts
- api/dbadapters/snowflake.ts
- api/dbadapters/sqldatawarehouse.ts
- cli/index.ts
- content/docs/guides/configuration.md
- protos/core.proto
- version.bzl
fixes https://github.com/dataform-co/dataform/issues/761
> Add a configurable query concurrency limit to all DB adapters.

- api/commands/build.ts
- api/commands/run.ts
- protos/core.proto
Context: https://app.intercom.com/a/apps/nnz2jx08/inbox/inbox/all/conversations/27441291632
> Make dependencies on non-table Declarations always cache-bust.

- api/commands/run.ts
for https://github.com/dataform-co/dataform-co/issues/7010
> Fix run resumption for RunResults with zero actions.

- api/BUILD
- api/dbadapters/redshift.ts
> Quick hacky fix for pg uncaught exceptions

- package.json
- yarn.lock
Required to merge https://github.com/dataform-co/dataform-co/pull/7410
for https://github.com/dataform-co/dataform-web-tracking/issues/245
> Upgrade cron-parser dependency.

- api/dbadapters/redshift.ts
for https://github.com/dataform-co/dataform/issues/914
> Release any pg.Clients that throw Errors which are not otherwise handled by the current query.

- components/spinner.scss
- components/spinner.tsx
Progresses https://github.com/dataform-co/dataform-co/issues/7432
For https://github.com/dataform-co/dataform/pull/923
> Add optional loading message to spinner

- components/spinner.tsx
Message was showing when it shouldn't have been, making spinners look janky
> Fix janky spinners

- api/dbadapters/bigquery.ts
To help with https://github.com/dataform-co/dataform-co/issues/7452
> Migrate BigQuery DB adapter to use the stream API.

- api/commands/query.ts
- api/commands/run.ts
- api/commands/test.ts
- api/dbadapters/bigquery.ts
- api/dbadapters/index.ts
- api/dbadapters/redshift.ts
- api/dbadapters/snowflake.ts
- api/dbadapters/sqldatawarehouse.ts
- api/utils/BUILD
- api/utils/results.ts
- package.json
- packages/@dataform/cli/BUILD
- tests/integration/bigquery.spec.ts
- tests/integration/redshift.spec.ts
- tests/integration/snowflake.spec.ts
- tests/integration/sqldatawarehouse.spec.ts
- yarn.lock
for https://github.com/dataform-co/dataform-co/issues/7452
> Add a byte-limit option to all DB adapter execute() methods.

- api/dbadapters/redshift.ts
We've been seeing issues where calling `dbadapter.close()` was hanging, probably due to various connections being in a strange state. This resolves both of those.
- When we encounter an error during processing the stream, we call `destroy(e)` with an error object, which causes appropriate cleanup to happen and releases the connection correctly in the normal error handler code.
- When we have processed enough data based on limits, we call `close()` on the cursor itself which is implied as the correct way per the pg docs and means the `"end"` even fires correctly.
> More fixes for handling redshift errors and cursors

- api/dbadapters/bigquery.ts
- core/column_descriptors.ts
- core/common.ts
- package.json
- protos/core.proto
- tests/integration/bigquery_project/definitions/example_view.sqlx
- version.bzl
- yarn.lock
Also updates BigQuery libraries to latest and uses in-built types.
Fixes #938
> BigQuery policy tag support

- components/step_indicator.tsx
Progresses https://github.com/dataform-co/dataform-co/issues/7627
enables https://github.com/dataform-co/dataform-co/pull/7645
Looks the same as what's currently used in the walkthrough, but now more reusable!
`test code`
> Make the step indicator a component

- components/step_indicator.scss
- components/step_indicator.tsx
Also uses appropriate css variable for color now
> Step indicator tweaks - work both in and out of CardActions block

- components/forms.tsx
And hide description div if not present
> Make formitem name optional

- api/dbadapters/bigquery.ts
- content/docs/warehouses/bigquery.md
- core/table.ts
- protos/core.proto
- tests/integration/bigquery.spec.ts
- tests/integration/bigquery_project/definitions/example_view.sqlx
- version.bzl
Fixes https://github.com/dataform-co/dataform-co/issues/7823
> Bigquery label metadata

- content/docs/warehouses/bigquery.md
It caught me out, I think this is clearer?
> clarify multiple labels

- api/dbadapters/bigquery.ts
Related to https://github.com/dataform-co/dataform-co/issues/7856
Noticed compiled query was missing in query evaluation, changed in #960 a few days ago I think
> Add missing query and incremental from query evaluation

- api/dbadapters/postgres.ts
- api/dbadapters/redshift.ts
- api/dbadapters/snowflake.ts
- tests/integration/postgres.spec.ts
- tests/integration/postgres_project/definitions/example_incremental.sqlx
- tests/integration/redshift.spec.ts
- tests/integration/redshift_project/definitions/example_incremental.sqlx
- tests/integration/snowflake.spec.ts
- tests/integration/snowflake_project/definitions/example_incremental.sqlx
for https://github.com/dataform-co/dataform-web-tracking/issues/254
> Fix COMMENT ON statements whose comment contains multiple single-quote characters.

- api/dbadapters/snowflake.ts
- tests/integration/snowflake.spec.ts
(and bring back temporarily removed integration test)
> Fix snowflake timeout issues, by turning off OCSP.

- examples/formatter/definitions/dollar_regex.sqlx
- sqlx/format.ts
- tests/sqlx/format.spec.ts
> Fix some odd behaviour when formatting certain strings

- common/strings/stringifier.ts
Useful for classes that require a stringifier, WDYT?
> Add string stringifier

- common/strings/stringifier.spec.ts
- common/strings/stringifier.ts
Wasn't meant to have a parameter. Also added short test, to follow pattern.
> Remove parameter from string stringifier, add test

- core/adapters/bigquery.ts
- core/adapters/redshift.ts
- core/adapters/sqldatawarehouse.ts
Fixes https://github.com/dataform-co/dataform-co/issues/7926
End of query comments were breaking incremental merge as it was commenting out the closing bracket
> Fix merge newlines

- api/dbadapters/postgres.ts
- api/ssh_tunnel_proxy.ts
- protos/profiles.proto
for https://github.com/dataform-co/dataform-co/issues/7616
> Add connection options for connecting to postgres using SSL with custom client/server certs.

- api/ssh_tunnel_proxy.ts
for https://github.com/dataform-co/dataform-co/issues/7616
> Make SSH tunnel code correctly handle error events.

- app/BUILD
- app/webpack.config.js
Speaking to some people about a bazel webpack rule and just wanted to fix this issue first.
> Support ibazel reloads on webpack app

- api/dbadapters/bigquery.ts
- api/dbadapters/postgres.ts
- api/dbadapters/redshift.ts
- api/dbadapters/snowflake.ts
- api/dbadapters/sqldatawarehouse.ts
- protos/core.proto
- tests/integration/bigquery.spec.ts
- tests/integration/postgres.spec.ts
- tests/integration/redshift.spec.ts
- tests/integration/snowflake.spec.ts
Progresses https://github.com/dataform-co/dataform-co/issues/7904
Follow on from https://github.com/dataform-co/dataform-co/pull/7934
> Remove primitiveDeprecated

- api/dbadapters/bigquery.ts
Context: https://dataform-users.slack.com/archives/CHMJK8MKM/p1600797202009200
> Correctly handle BQ tables with zero columns.

- api/BUILD
- api/dbadapters/snowflake.ts
- scripts/cloudbuild/bazel_test
- tests/integration/BUILD
for https://github.com/dataform-co/dataform-co/issues/6939
> Refactor Snowflake parameters into flags, and revert those parameters to their defaults.

- api/utils/error_parsing.ts
- tests/api/api.spec.ts
- tests/integration/bigquery.spec.ts
- tests/integration/snowflake.spec.ts
- tests/integration/sqldatawarehouse.spec.ts
Fixes https://github.com/dataform-co/dataform-co/issues/7723
Correct me if I'm wrong:
* Our SQL code preview component line and column number start at 1.
* BQ's column and line number start at 1.
* Snowflakes column number starts at 0 but line number start at 1.
> Snowflake error parsing fix & test

- WORKSPACE
- cli/BUILD
- scripts/publish
- include Git, which is important for Git-based NPM deps
- publish a `latest` tag
> Publish a better CLI Docker image.

- api/commands/run.ts
- api/dbadapters/bigquery.ts
- api/dbadapters/index.ts
- package.json
- yarn.lock
fixes https://github.com/dataform-co/dataform/issues/1009
> Set labels on BQ jobs.

- core/adapters/bigquery.ts
- core/adapters/redshift.ts
- core/adapters/snowflake.ts
- core/adapters/sqldatawarehouse.ts
- core/session.ts
- core/table.ts
- protos/core.proto
- tests/integration/snowflake_project/definitions/example_view.sqlx
- version.bzl
fixes https://github.com/dataform-co/dataform/issues/711
> Add support for Snowflake secure views.

- docs/content_tree.ts
Replacing https://github.com/dataform-co/dataform/pull/1024
> Fix fivetran repo name.

- content/docs/dataform-web/git-access-tokens.md
- more clearly list the permissions required
> making instructions clearer

- content/docs/guides/configuration.md
- core/compilers.ts
- core/gen_index.ts
- core/session.ts
- packages/@dataform/sql/index.ts
- protos/core.proto
- tests/core/backslashes-act-literally.js.test
- tests/core/backticks-are-escaped.js.test
- tests/core/basic-syntax.js.test
- tests/core/js-placeholder-strings-inside-sql-strings.js.test
- tests/core/strings-act-literally.js.test
- tests/integration/bigquery_project/dataform.json
- tests/integration/bigquery_project/definitions/sample_data.sql
- tests/integration/bigquery_project/definitions/sample_data.sqlx
- tests/integration/postgres_project/dataform.json
- tests/integration/postgres_project/definitions/sample_data.sql
- tests/integration/postgres_project/definitions/sample_data.sqlx
- tests/integration/redshift_project/dataform.json
- tests/integration/redshift_project/definitions/sample_data.sql
- tests/integration/redshift_project/definitions/sample_data.sqlx
- tests/integration/snowflake_project/dataform.json
- tests/integration/snowflake_project/definitions/sample_data.sql
- tests/integration/snowflake_project/definitions/sample_data.sqlx
- tests/integration/sqldatawarehouse_project/dataform.json
- tests/integration/sqldatawarehouse_project/definitions/sample_data.sqlx
- version.bzl
for https://github.com/dataform-co/dataform/issues/1033
> Expose ProjectConfig as a public API in @dataform/core, and add support for custom variables.

- content/docs/dataform-web/scheduling/environments.md
for https://github.com/dataform-co/dataform/issues/1033
> Add documentation on environmentName/scheduleName vars.

- docs/pages/_document.tsx
for https://github.com/dataform-co/dataform-co/issues/8273
> Redirect segment traffic as a test.

- api/commands/run.ts
- protos/core.proto
- tests/api/api.spec.ts
for https://github.com/dataform-co/dataform-co/issues/8280
> Attach Target to ActionResult to make it easier to match with ExecutionAction.

- docs/pages/_document.tsx
for https://github.com/dataform-co/dataform-co/issues/8273
> Revert to original Segment source.

- tools/nginx/spa/nginx.conf
needed by https://github.com/dataform-co/dataform-co/pull/8318
for https://github.com/dataform-co/dataform-co/issues/8273
> Change SPA nginx config for new inline script hash.

- readme.md
fixes https://github.com/dataform-co/dataform/issues/1048
> Fix CLI docs link.

- core/adapters/snowflake.ts
- core/session.ts
- core/table.ts
- protos/core.proto
- tests/api/api.spec.ts
- tests/core/core.spec.ts
- tests/integration/snowflake.spec.ts
- tests/integration/snowflake_project/definitions/example_transient.sqlx
> Add support for transient tables in snowflake

- core/adapters/snowflake.ts
- core/session.ts
- core/table.ts
- protos/core.proto
- tests/core/core.spec.ts
- tests/integration/snowflake.spec.ts
- tests/integration/snowflake_project/definitions/example_cluster_by.sqlx
- version.bzl
Fixes #1027 
Bumps version to 1.14
> Support snowflake clustering keys

- WORKSPACE
This lets me build our code again. 🤷
> Upgrade protobuf dependency.

- api/commands/prune.ts
- cli/index.ts
- protos/core.proto
- protos/schedules.proto
- tests/api/api.spec.ts
Progresses https://github.com/dataform-co/dataform-co/issues/8393
> Add an include dependents option to pruning

- core/table.ts
- tests/api/examples.spec.ts
- tests/integration/bigquery.spec.ts
- version.bzl
fixes https://github.com/dataform-co/dataform-co/issues/8198
> Namespace auto-assertions by the schema of their associated table.

- core/table.ts
- examples/common_v2/definitions/example_table_with_tags.sqlx
- examples/common_v2/definitions/has_compile_errors/disabled_assertion.sqlx
- tests/api/examples.spec.ts
- version.bzl
fixes https://github.com/dataform-co/dataform/issues/1044
> Disable auto-assertions if their associated table is disabled.

- core/table.ts
- tests/api/examples.spec.ts
- tests/integration/bigquery.spec.ts
- tests/integration/bigquery_project/definitions/sample_data_2.sqlx
- tests/integration/postgres.spec.ts
- tests/integration/postgres_project/definitions/sample_data_2.sqlx
- tests/integration/redshift.spec.ts
- tests/integration/redshift_project/definitions/sample_data_2.sqlx
- tests/integration/snowflake.spec.ts
- tests/integration/snowflake_project/definitions/sample_data_2.sqlx
- tests/integration/sqldatawarehouse_project/definitions/sample_data_2.sqlx
- version.bzl
fixes https://github.com/dataform-co/dataform/issues/1029
> Bring back 'uniqueKeys' auto-assertions.

- core/table.ts
- examples/common_v2/definitions/sample_data.sqlx
- tests/api/examples.spec.ts
- version.bzl
fixes https://github.com/dataform-co/dataform/issues/942
> Allow empty pre/post ops.

- version.bzl
Relevant PR: https://github.com/dataform-co/dataform/pull/1062
> Bump version for semi colon PR

- api/BUILD
- api/commands/compile.ts
- api/commands/run.ts
- api/utils/BUILD
- api/utils/run_cache.ts
- api/vm/gen_index_config.ts
- api/vm/legacy_gen_index.ts
- common/protos/BUILD
- common/protos/index.ts
- core/BUILD
- core/gen_index.ts
- core/session.ts
for https://github.com/dataform-co/dataform-co/issues/8280
> Add protobuf utils to open source. Use them to clone RunResult before passing it to listeners.

- api/dbadapters/postgres.ts
- api/dbadapters/redshift.ts
- api/dbadapters/snowflake.ts
fixes https://github.com/dataform-co/dataform/issues/1054
> Fix query cancellation for Snowflake.

- package.json
- yarn.lock
Reverts dataform-co/dataform#1076
for https://github.com/dataform-co/dataform-co/issues/8598
> Revert "Bump BQ version past fix for 'Job Already Exists' error."

- package.json
- yarn.lock
for https://github.com/dataform-co/dataform-co/issues/8598
> Pin BigQuery nodejs client to 5.3

- core/table.ts
- version.bzl
fixes https://github.com/dataform-co/dataform-co/issues/8591
> Stop validating pre/post ops. Start validating incremental queries.

- packages/@dataform/sql/index.ts
- sql/index.ts
- sql/integration.spec.ts
- sql/timestamps.ts
sql.timestamps.diff
sql.windowFunction
sql.surrogateKey
> More sql functions

- sql/README
Any thoughts on the style before I add more?
> first commit of readme

- api/commands/compile.ts
- core/session.ts
- protos/core.proto
- tests/api/examples.spec.ts
- version.bzl
for https://github.com/dataform-co/dataform-co/issues/8698
> Add a databaseSuffix configuration variable.

- package.json
- yarn.lock
To move past the fix for https://github.com/googleapis/nodejs-bigquery/issues/888
> Upgrade BQ client library to 5.5.0.

- api/dbadapters/bigquery.ts
fixes https://github.com/dataform-co/dataform-co/issues/8807
> Include 'database' in Targets returned from BigQueryDbAdapter.tables(...).

- core/assertion.ts
- core/operation.ts
- version.bzl
Fixes https://github.com/dataform-co/dataform-web-tracking/issues/282
Issue was actually happening when schema was put as well as database in an action's config; the schema was resetting the database back to the default database as the database proto option wasn't set
Was also happening with assertions, not just operations. Also did some tidying too while at it.
> Fix database action overrides

- content/docs/guides/configuration.md
> Update run caching documentation

- core/assertion.ts
- core/operation.ts
- version.bzl
fixes https://github.com/dataform-co/dataform-co/issues/8329
> Add the when() function to all action types.

- components/blueprint/core.global.scss
Progresses https://github.com/dataform-co/dataform-co/issues/8697
> Fix primary menu colors

- api/commands/run.ts
- api/dbadapters/bigquery.ts
- protos/core.proto
fixes https://github.com/dataform-co/dataform/issues/1125
> Force run-cache break if a dataset's input has a streaming buffer.

- package.json
- redis/client.ts
- yarn.lock
Solution to fixing https://github.com/dataform-co/dataform-co/pull/9012
> Downgrade handy redis to 1.8.3

- content/docs/dataform-web/tutorials/101.md
- content/docs/getting-started-tutorial/set-up.md
- content/docs/introduction/modern-data-stack.md
Removed references to other warehouses in docs.
> Docs update

- content/docs/getting-started-tutorial/committing-changes.md
While reading the documentation, I saw some typos so I made a quick PR.
> Fixing small typos on Committing changes page

- api/commands/run.ts
Notes:
- stop recalculating finished / successfully finished actions all the time; instead, be stateful
- ideally these new `Set<string>` instances would be `StringifiedSet<dataform.ITarget>` instances, but `ExecutionAction` still doesn't have dependency target information, so that's not possible
- it's probably possible to do this looping around `this.pendingActions` less frequently, but (a) I doubt it actually costs that much, (b) it will likely slow down end-to-end execution, and (c) that will require a bit more refactoring; I'd like to see how this change performs first
> Speed up calculation of executable/skippable actions.

- tools/helm/repository_rules.bzl
Fixes #1166 .
This PR should ensure that no cache / config files are leaked outside bazel workspace, during helm_chart rule execution. 
*Note*: The update of helm binary was necessary, due to bug in helm (see: [link](https://github.com/helm/helm/pull/8158)).
Update to 3.2.2 release should be sufficient, but I have tested it on 3.4.2 and everything seemed to work fine.
> Bazel repo_rule helm_chart - Fix leaking cache & config

- content/docs/best-practices/start-your-dataform-project.md
Changed "Analytics" to "Reporting" to match what is shown in the folder_example.png image.
> Changed "Analytics" to "Reporting"

- api/BUILD
- api/commands/compile.ts
- core/gen_index.ts
- package.json
- packages/@dataform/cli/BUILD
- yarn.lock
related to https://github.com/dataform-co/dataform-web-tracking/issues/287
This isn't actually the cause of that bug, because the broken merge that bug is referring to happens at a higher level, but I'm fixing this up for completeness.
> Merge project config & overrides correctly.

- package.json
- yarn.lock
https://github.com/dataform-co/dataform/security/dependabot/yarn.lock/prismjs/open
> Remediate prismjs Dependabot alert.

- core/adapters/bigquery.ts
- tests/api/api.spec.ts
fixes https://github.com/dataform-co/dataform/issues/1201
> Wrap BQ column names in backticks in generated INSERT statements.

- content/docs/packages/create-packages.md
dataform-package-base href was broken
> Small fix in URL for base package repo

- cli/BUILD
- cli/index.ts
- package.json
- packages/@dataform/cli/BUILD
- version.bzl
- yarn.lock
fixes https://github.com/dataform-co/dataform/issues/1246
> Implement a --timeout flag for the CLI. Make the CLI options much more type-safe.

- api/commands/build.ts
- protos/core.proto
- tests/api/api.spec.ts
Populate the field only at this point.
> Add dependencyTargets to execution action proto

- api/commands/run.ts
- tests/api/api.spec.ts
Currently if setMetadata fails for any reason, it can kill the entire run with an unclear error message. This at least constrains those errors to the action.
> Constraint setMetadata errors to the action that caused them

- core/session.ts
- version.bzl
utils.getCallerFile is unable to resolve the current file in session.ts, which it looks like it was never designed to do.
> Explicitly set path in dataform.json location validation error

- core/session.ts
- core/table.ts
- tests/api/examples.spec.ts
- version.bzl
(with some automatic formatting fixes...)
> Make table level assertions have the same tags as the table

- .gitignore
- api/commands/credentials.ts
- cli/index.ts
- version.bzl
Fixes https://github.com/dataform-co/dataform/issues/1358
> Fix missing credentials error by adding it as the default option

- api/commands/run.ts
- api/dbadapters/bigquery.ts
- api/dbadapters/index.ts
- cli/index.ts
- protos/core.proto
- tests/api/api.spec.ts
- tests/integration/bigquery.spec.ts
Fixes https://github.com/dataform-co/dataform/issues/1413
Can see this running when testing via the CLI
> Add job prefix option to the CLI

- core/compilers.ts
- tests/core/backslashes-act-literally.js.test
- tests/core/backticks-are-escaped.js.test
- tests/core/basic-syntax.js.test
- tests/core/js-placeholder-strings-inside-sql-strings.js.test
- tests/core/strings-act-literally.js.test
resolves #1484 
If you know of any other places where I should add a test, any advice would be appreciated.
> Add `schema` & `database` to contextFunctions in compile time

- readme.md
> Fix image link in readme.md

- sqlx/lexer.ts
> Make lexer typings safe

- sandbox/vm/create_config.ts
- version.bzl
See https://issuetracker.google.com/issues/296162656#comment3 for details.
> Fix `@dataform/cli` to be compatible with versions of `@dataform/core` <= `2.6.5`.

- api/commands/compile.ts
- sandbox/compile_executor.cc
- sandbox/worker/BUILD
- A few changes to get cross-repo bazel paths working
- Reintroduce stdout/stderr logging
> Sandbox2 wrapper updates for web integration

- package.json
- packages/@dataform/cli/BUILD
- sqlx/BUILD
- sqlx/format.ts
- yarn.lock
> Update SQLX formatting to use typeid-js instead of uuidv4

- core/index.ts
- core/main.ts
- protos/core.proto
- yarn.lock
I will merge this with a merge commit, to preserve history.
> Merge main to main_v3

- package.json
- yarn.lock
This is to get an updated dependency on axios so that dependabot security alerts stop happening.
> Update version of snowflake-sdk to 1.9.1

- vscode/BUILD
Vscode has been so neglected that it can no longer build itself. With this it can!
> Make Vscode Buildable Again

- core/session.ts
- tests/core/core.spec.ts
- version.bzl
fixes https://github.com/dataform-co/dataform/issues/1642
> Fix `ActionIndex.find()` when callers pass an unknown database/schema value.

- core/session.ts
- tests/core/core.spec.ts
Will merge with a merge commit, in order to preserve history
> Merge main to main_v3 5

- cli/console.ts
- cli/index.ts
Fixes https://github.com/dataform-co/dataform/issues/1217
> Prevent confusion around JSON printing of the execution graph

- core/actions/assertion.ts
- core/actions/operation.ts
- core/actions/table.ts
- core/main_test.ts
Fixes https://github.com/dataform-co/dataform/issues/1464
> Add bool argument to disable, default true to keep the API the same

- contributing.md
Fixes https://github.com/dataform-co/dataform/issues/1483
> Update contributing tests guide to just test core

- core/main_test.ts
Useful to have before modifying how SQLX config options are validated, such as https://github.com/dataform-co/dataform/pull/1731
> Add tests for locking in SQLX config options validity

- cli/api/dbadapters/bigquery.ts
- cli/index.ts
Fixes https://github.com/dataform-co/dataform/issues/1739
> Fix bigquery dryrun

- docs/configs-reference.md
- scripts/regenerate_docs
Also add a comment about camel casing.
> Regenerate configs reference with camelCase fields

- core/actions/data_preparation.ts
- core/main_test.ts
- protos/data_preparation.proto
Moved data preparation into another package.
> Sync proto structure and message names for data preparation.

- cloudbuild-version.yaml
Fixing grammatically wrong name of our automated PRs.
> Fixing the name for automaticallty created PR

- version.bzl
Updating NPM package version to 3.0.4
> Publish a new NPM versions

- cloudbuild-publish.yaml
- cloudbuild-version.yaml
- scripts/publish
As part of publishing new NPM package every month we also need to add release notes for these published new versions on github. 
In this change. I am using Github Cli to create a new release when a new version is published to NPM.
> Creating release notes as part of publishing process

- version.bzl
Updating the patch version to test our pipelines.
> Bump the patch version to 3.0.6

- version.bzl
Bumping the patch version to update release notes for latest version and doing so by pipeline.
> Bump the patch version

- version.bzl
Updating NPM package version to 3.0.8
> Publishing Dataform security patches

- scripts/create_npmrc
- scripts/run_tests_on_cloudbuild
Update Airlock from staging to trusted to use verified dependencies.
> Update Airlock url

- .github/CODEOWNERS
This should automatically request a review from a Dataform team member, when anyone opens a PR https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners
> Add a codeowners file, for automatic review requesting

- core/actions/incremental_table.ts
- core/actions/index.ts
- core/actions/view.ts
- core/main_test.ts
Restructuring test to be more DAMP now tests the issue
> Fix string value for uniqueKey assertions, tidy tests

- vscode/README.md
- vscode/package.json
Per internal discussion, deprecate and suggest alternative
> Deprecation notice on the vscode extension

- core/actions/data_preparation.ts
- core/main_test.ts
This uses the file name as the target.
> Add support for an empty data preparation. 

- core/actions/assertion.ts
- core/actions/data_preparation.ts
- core/actions/declaration.ts
- core/actions/incremental_table.ts
- core/actions/index.ts
- core/actions/notebook.ts
- core/actions/operation.ts
- core/actions/table.ts
- core/actions/test.ts
- core/actions/view.ts
- core/session.ts
- core/utils.ts
This removes some confusing interface usage that wasn't actually type safe
> Remove iactionproto

- core/actions/data_preparation.ts
- core/compilers.ts
- core/main_test.ts
- core/session.ts
Removed now unused methods/classes.
> Update Data Preparation compilation to use constant for replacement of validation calls

- version.bzl
Includes https://github.com/dataform-co/dataform/pull/1935
> Release version 3.0.16

- version.bzl
> Release 3.0.19

- version.bzl
- Graceful exit in CLi when there is no actions to run #1965
- Materialized views fix from #1970
> Bump version to 3.0.21

- version.bzl
Version update to roll out Iceberg changes. More details in [#2009](https://github.com/dataform-co/dataform/pull/2009).
> Bump version to 3.0.29

- version.bzl
Includes naming fix from https://github.com/dataform-co/dataform/pull/2022
> Bump version to 3.0.33

- version.bzl
Includes changes in https://github.com/dataform-co/dataform/pull/2030.
> Bump version to 3.0.35
